### ISSUE TITLE
Wrong reference to clients registration overview

### ISSUE THREAD

**Issue by witekest** [uyuni-project/uyuni-docs#1013]
## Documentation Update Required

The page describing [openSUSE Client registration](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-opensuse.html#_register_clients) has wrong reference at the bottom of the page. [Client Registration Overview](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/registration-overview.html) is not helpful at that place. It does not include information to further steps and is not integrated into the table of contents.

## What does the documentation say now?

For more information on registering your clients, see client-configuration:registration-overview.adoc.

## What change is required?

Clearly understandable configuration steps.

## Internal SUSE Reporters

@witekest

**Comment by 0rnela** [comment]
We are using the link pointing to the parent chapter from which all information about client registration can be accessed.  One possible change is to add a link to a more specific chapter, but after recent books reorganization, the chapter about registration methods is now clearly seen at top of the navigation bar structure. 

Closing this issue, but will include this link on the list for general documentation review.
