### ISSUE TITLE
PDF downloads of Uyuni Documentation are not available

### ISSUE THREAD

**Issue by srinidhibs** [uyuni-project/uyuni-docs#1014]
## Documentation Update Required

Under the [Available Documentation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/index.html#_available_documentation) table of Uyuni Documentation, clicking on any of the PDF links is showing a Github 404 error page.

## What does the documentation say now?

[Page not found · GitHub Pages](https://www.uyuni-project.org/uyuni-docs/en/pdf/uyuni_reference_guide.pdf) 

![image](https://user-images.githubusercontent.com/1150476/124432290-165a2380-dd8f-11eb-9879-418ecb645146.png)

## What change is required?

Please upload the missing PDF files for the [English](https://github.com/uyuni-project/uyuni-docs/tree/gh-pages/en) language. I can see a pdf directory for the Japanese, Korean (?), and Simplified Chinese languages.

## Subject Matter Expert (SME)

I don't know.

## Version

Which version of the software is this feature/update expected to land in (if known)?
2021.06

Which version of the documentation must this feature/update land in (if known)?
2021.06

Does the content need to be backported to previous documentation versions (if known)?
No.

**Comment by jcayouette** [comment]
Woops, we did not update the index page for the new translations. I will setup a few asciidoc attributes that can be adjusted in our entities files before a build (if required) to help prevent this. Thanks! @srinidhibs
