### ISSUE TITLE
SUMA 4.2 docs on doc.suse.com have the wrong URL in their Canonical <link> tags

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#1032]
## Documentation Update Required

Since we've uploaded the newly-localized SUMA 4.2 docs, the Canonical URLs are wrong, they lack the `/en/` as part of the URL:

```
    <link rel="canonical" href="https://documentation.suse.com/suma/4.2/suse-manager/upgrade/proxy-uyuni.html">
```

This is actually really bad -- because this means search engines are going to be indexing a path that is actually just a 404 page! This is a practical issue too, as our current report on 404 issues from Google Analytics is showing.

## Subject Matter Expert (SME)

@paususe / @jcayouette / @keichwa 

## Version

SUMA 4.2

**Comment by jcayouette** [comment]
Fixed in 4.2.2
