### ISSUE TITLE
Unnecessary PDFs in SUMA 4.2's doc.suse.com tree 

### ISSUE THREAD

**Issue by ghost** [uyuni-project/uyuni-docs#1038]
## Documentation Update Required

SUMA 4.2's current tree is a little weird when it comes to PDFs.

1. `en/pdf/` and `pdf/` are entirely separate dirs. I think `en/pdf/` contains newer documents. 
2. As an exception to that, the API Guide is only available from the `pdf/` dir (and still uses the suse2013 stylesheets).
3. All guides (except the API Guide) are available under all language-specific dirs. However, only the Client Configuration Guide, Installation Guide, and Upgrade Guide are actually translated. The other ones are just copies of the English guides.

Is there an easy way to clean this up for you?

Ftr, this is the current tree for 4.2 (with non-PDF parts snipped):

```
.
├── api
│   ├── [No PDFs here whatsoever]
│   [...]
├── en
│   ├── pdf
│   │   ├── suse_manager_administration_guide.pdf
│   │   ├── suse_manager_client-configuration_guide.pdf
│   │   ├── suse_manager_installation_guide.pdf
│   │   ├── suse_manager_large-deployments_guide.pdf
│   │   ├── suse_manager_quickstart-public-cloud_guide.pdf
│   │   ├── suse_manager_quickstart-sap_guide.pdf
│   │   ├── suse_manager_reference_guide.pdf
│   │   ├── suse_manager_retail_guide.pdf
│   │   ├── suse_manager_salt_guide.pdf
│   │   └── suse_manager_upgrade_guide.pdf
│   [...]
├── ja
│   ├── pdf
│   │   ├── suse_manager_administration_guide.pdf
│   │   ├── suse_manager_client-configuration_guide.pdf
│   │   ├── suse_manager_installation_guide.pdf
│   │   ├── suse_manager_large-deployments_guide.pdf
│   │   ├── suse_manager_quickstart-public-cloud_guide.pdf
│   │   ├── suse_manager_reference_guide.pdf
│   │   ├── suse_manager_retail_guide.pdf
│   │   ├── suse_manager_salt_guide.pdf
│   │   └── suse_manager_upgrade_guide.pdf
│   [...]
├── ko
│   ├── pdf
│   │   ├── suse_manager_administration_guide.pdf
│   │   ├── suse_manager_client-configuration_guide.pdf
│   │   ├── suse_manager_installation_guide.pdf
│   │   ├── suse_manager_large-deployments_guide.pdf
│   │   ├── suse_manager_quickstart-public-cloud_guide.pdf
│   │   ├── suse_manager_reference_guide.pdf
│   │   ├── suse_manager_retail_guide.pdf
│   │   ├── suse_manager_salt_guide.pdf
│   │   └── suse_manager_upgrade_guide.pdf
│   [...]
├── pdf
│   ├── 4.2_pdf_susemanager_api_doc_color_en.pdf
│   ├── suse_manager_administration_guide.pdf
│   ├── suse_manager_client-configuration_guide.pdf
│   ├── suse_manager_installation_guide.pdf
│   ├── suse_manager_large-deployments_guide.pdf
│   ├── suse_manager_quickstart-public-cloud_guide.pdf
│   ├── suse_manager_quickstart-sap_guide.pdf
│   ├── suse_manager_reference_guide.pdf
│   ├── suse_manager_retail_guide.pdf
│   ├── suse_manager_salt_guide.pdf
│   └── suse_manager_upgrade_guide.pdf
└── zh_CN
    ├── pdf
    │   ├── suse_manager_administration_guide.pdf
    │   ├── suse_manager_client-configuration_guide.pdf
    │   ├── suse_manager_installation_guide.pdf
    │   ├── suse_manager_large-deployments_guide.pdf
    │   ├── suse_manager_quickstart-public-cloud_guide.pdf
    │   ├── suse_manager_reference_guide.pdf
    │   ├── suse_manager_retail_guide.pdf
    │   ├── suse_manager_salt_guide.pdf
    │   └── suse_manager_upgrade_guide.pdf
    │   [...]
```

## Subject Matter Expert (SME)

@paususe / @jcayouette / @keichwa 

## Version

SUMA 4.2

---

*(Issue partly via @emaksy)*

**Comment by paususe** [comment]
> ## Documentation Update Required
> SUMA 4.2's current tree is a little weird when it comes to PDFs.
> 
> 1. `en/pdf/` and `pdf/` are entirely separate dirs. I think `en/pdf/` contains newer documents.

That `pdf/` directory must be a remnant from the past. It is not generated by builds since months ago.

> 2. As an exception to that, the API Guide is only available from the `pdf/` dir (and still uses the suse2013 stylesheets).

That's right, the API guide is only available in English so we have a single copy. We could move it to `en/pdf/` with some re-linking effort.

> 3. All guides (except the API Guide) are available under all language-specific dirs. However, only the Client Configuration Guide, Installation Guide, and Upgrade Guide are actually translated. The other ones are just copies of the English guides.

That's right. It's because of the way po4a (the tool we use to convert from AsciiDoc to gettext and back) and antora (the documentation build system) work. There is no way around that.

**Comment by sknorr** [comment]
>> 1.  en/pdf/ and pdf/ are entirely separate dirs. I think en/pdf/ contains newer documents.
> That pdf/ directory must be a remnant from the past. It is not generated by builds since months ago.

Looking at Git, you may be right about that, but in any case, it was not cleared out yet after the dir structure changed between beta and final release.

>>  As an exception to that, the API Guide is only available from the pdf/ dir (and still uses the suse2013 stylesheets).
> That's right, the API guide is only available in English so we have a single copy. We could move it to en/pdf/ with some re-linking effort.

Moving the API Guide sounds good. I can create a redirect for it.

>> All guides (except the API Guide) are available under all language-specific dirs. However, only the Client Configuration Guide, Installation Guide, and Upgrade Guide are actually translated. The other ones are just copies of the English guides.
> That's right. It's because of the way po4a (the tool we use to convert from AsciiDoc to gettext and back) and antora (the documentation build system) work. There is no way around that.

Essentially, you're running into the same issue issue that we do with DAPS & translated HTML, I guess. Sucks but is understandable. However, I was wondering if the pseudo-translated PDFs were an absolute necessity or if they could be deleted after Antora is finished. I am trying to make our sitemap.xml more useful to search engines and not exposing these unnecessary duplicated PDFs in any would be good.

**Comment by jcayouette** [comment]
Its a simple clean up, but in the future we will be translating these as well. 

We can:

1. Keep the English copies
2. Remove English pdf versions and just use hard links for english only documents.

**Comment by sknorr** [comment]
> Its a simple clean up post build, I could even script it, 

Yes, please do script this.
In fact, it should be doable in a single command currently:

```
repo=/path/to/repo/suma/4.2/

rm $repo/{ja,ko,zh}/suse_manager_{administration_guide,large-deployments_guide,quickstart-public-cloud_guide,reference_guide,retail_guide,salt_guide}.pdf
```

> but in the future we will most likely be translating these as well.

Futures are uncertain and hopefully the `rm` command(s) should be simple to update when time arrives. With SLES, we know that only Simplified Chinese ever got a full translation.

**Comment by 0rnela** [comment]
@jcayouette -- is this still an issue? In my recent documentation builds, I could see only one PDF directory.

**Comment by jcayouette** [comment]
Fixed. Removed redundant pdfs and updated xmlconfig.
