### ISSUE TITLE
Missing Channel information for Ubuntu 20

### ISSUE THREAD

**Issue by gvaynapel** [uyuni-project/uyuni-docs#1040]
On this link: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu.html
It is missing all of the ubuntu 20 lts channels. It also looks like the channels for 16.04 and 18.04 is also wrong.

**Comment by keichwa** [comment]
We now have ubuntu 20 channels.  16.04 and 18.04 are moved to https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu-old.html.  Can you please check whether this is now fixed?

**Comment by gvaynapel** [comment]
It is fixed! Thank you.
