### ISSUE TITLE
Pages under modules/retail/pages/snippets have no title, but get own HTML file

### ISSUE THREAD

**Issue by ghost** [uyuni-project/uyuni-docs#1054]
## Documentation Update Required

The snippets in https://github.com/uyuni-project/uyuni-docs/tree/master/modules/retail/pages/snippets do not have page titles. However, they each come out as an HTML page, using the page title "Untitled :: SUSE Manager Documentation". That seems suboptimal. E.g.: https://documentation.suse.com/suma/4.2/en/suse-manager/retail/snippets/add_channels_wizard.html

## What change is required?

Add a title to those pages or make sure they are embedded in a larger page.

## Subject Matter Expert (SME)

Apparently ~@keichwa (?)~ @jcayouette 

## Version

4.2

**Comment by 0rnela** [comment]
These are all snippets and as do not necessatily need not need title - procedure title should be ok.

@keichwa @jcayouette -- please correct me if I am wrong.

I had checked a number of these snippets though and have found that only 3 are actually used from within the existing documentation pages. I will investigate what happened with the others and why they are written, but not used as snippets.

**Comment by keichwa** [comment]
Thanks for attacking this, @0rnela .  The snippet world is a hard place, at least for an alien as me! :-)

**Comment by sknorr** [comment]
Re: you original text:
> These are all snippets and as do not necessatily need not need title - procedure title should be ok

A good HTML `<title>` tag would really be good for every page. I am not asking for more :)

**Comment by jcayouette** [comment]
Thanks Stefan, Ill look into this.

**Comment by jcayouette** [comment]
Using an _ on a document prevents it from being published and searchable.
