### ISSUE TITLE
Japanese PDF Layout issues 

### ISSUE THREAD

**Issue by PadraigDillon1** [uyuni-project/uyuni-docs#1066]
## Documentation Update Required

Client Config, Installation and Upgrade Guides for Japanese not displaying correctly in the PDF's posted to documentation.sus.com

## What does the documentation say now?

See screenshot for example of layout issues
![image](https://user-images.githubusercontent.com/76781279/127303565-2ebb75a1-324f-41f4-943f-d570785aed36.png)

## What change is required?

Do we need to use a different font for Japanese?

## Version

4.2

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by jcayouette** [comment]
Corrected in 4.2.2 release.
