### ISSUE TITLE
In builds for doc.suse.com, stop including a few files (robots, sitemap, 404 page, index redirect)

### ISSUE THREAD

**Issue by ghost** [uyuni-project/uyuni-docs#1072]
## Documentation Update Required

Similar to the previous report about unnecessary PDFs (#1038), it would be great if we could get rid of a few things in the DSC builds of the docs, so there's less of a need to add quirks to our redirects/sitemap builder for stuff that is not useful when you're not running the server yourself:

* `sitemap.xml`
* `robots.txt`
* `index.html` at the base level which is just an HTML-based redirect to `suse-manager/index.html`
* `404.html`

We have submitted the redirect `index.html` as part of our sitemap and Google finds them rather problematic because they include a `<meta name=robots content=noindex>` tag.

## What change is required?

Remove these files as part of the Antora build process for DSC.

## Subject Matter Expert (SME)

@jcayouette 

## Version

4.2, 4.1, 4.0

**Comment by jcayouette** [comment]
@sknorr Thanks adding it to our ToDo list on release day.

**Comment by keichwa** [comment]
@jcayouette can we close it here?

**Comment by 0rnela** [comment]
Closing, based on the PR mentioned above.
