### ISSUE TITLE
Page titles have underscore suffixes

### ISSUE THREAD

**Issue by SchoolGuy** [uyuni-project/uyuni-docs#1085]
## Documentation Update Required

Underscores should be removed from page titles and links.

- https://www.uyuni-project.org/uyuni-docs/en/uyuni/reference/spacecmd/activationkey_.html
- https://documentation.suse.com/suma/4.2/en/suse-manager/reference/spacecmd/whoami_.html
- ...

## What does the documentation say now?

Both internal and external docs are having underscores in multiple files in the `spacecmd` reference.

## What change is required?

Remove the underscores.

## Subject Matter Expert (SME)

I don't know who that should be.

## Version

Uyuni Master & SUMA 4.2 at least

**Comment by 0rnela** [comment]
Thanks @SchoolGuy, it will be taken care of.

**Comment by 0rnela** [comment]
The task has now been been completed.
