### ISSUE TITLE
Clarification, how to renew the expired GPG key

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni-docs#1087]
## Documentation Update Required

Need some clarification, how to renew the expired GPG key.

## What does the documentation say now?

https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/repo-metadata.html

## What change is required?

Add the correct method, what need to do if the key expire.

see this issue: https://github.com/uyuni-project/uyuni/issues/4101

**Comment by 0rnela** [comment]
Closing, based on the PR above.
