### ISSUE TITLE
Clicking on banner produces 404

### ISSUE THREAD

**Issue by BloodyIron** [uyuni-project/uyuni-docs#1159]
On this page (and probably others): https://www.uyuni-project.org/uyuni-docs/en/uyuni/quickstart-public-cloud/qs-publiccloud-overview.html

When you click on the banner in the top left, it takes you to a 404 page. I suspect that's not working as intended ;)

**Comment by jcayouette** [comment]
Correct, fixed with Uyuni-2021.09 closing.

**Comment by BloodyIron** [comment]
You're welcome! :)
