### ISSUE TITLE
Please add Documentation how to handle "Non-flat Debian repositories with apt wrapper plugin"

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#1162]
## Documentation Update Required
Please add Documentation for PR https://github.com/uyuni-project/uyuni/pull/3921 "Non-flat Debian repositories handling with apt wrapper plugin"

**Comment by Shirocco88** [comment]
Hint: IMHO this feature will be part of Uyuni-2021.10.

**Comment by keichwa** [comment]
it is merged now
