### ISSUE TITLE
"Edit this page" links use file:// URLs

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#1292]
## Documentation Update Required

The following documents from docs.suse.com (still) include "Edit this page" links at the top that link to `file:///home/...` rather than a GitHub URL:

* SUMA 4.2 _API Guide_: https://documentation.suse.com/suma/4.2/api/suse-manager/index.html
* All SUMA 4.1 docs: https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/administration/admin-overview.html

Most SUMA 4.2 docs do not include the link at all, so I guess there's no issue there.

## What change is required?

Fix links from `file://` URL to `https://github.com/uyuni-project/uyuni-docs/edit/...`

## Subject Matter Expert (SME)

@jcayouette 

## Version

* 4.1.12
* 4.2.3 & the WIP PR for v4.2.4

**Comment by sknorr** [comment]
[cc @jfaltenbacher]

**Comment by 0rnela** [comment]
Checked the links and they are pointing to 
href="https://github.com/.... pages.
