### ISSUE TITLE
Enhance RH clients section

### ISSUE THREAD

**Issue by raulosuna** [uyuni-project/uyuni-docs#1301]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

Customer could not add RH clients with the documentation. In a remote session, I struggled myself to do it and took my some time.

## What does the documentation say now?

No part of the documentation is wrong, at least that I could find in a quick look. However I would add more information

## What change is required?

First of all, no mention to whether "Enable GPG Check" should be used in the channel section when adding the custom channel. This is marked by default, I'm not sure whether it's required to remove it (I did it). In the channel section, this also enabled by default and this definitely needs to be removed when dealing with channels.
In addition, I would add a warning that when getting the URL to be used in the repository section, this can contain environment variables, such as $releasever (which should be exchanged for "7Server", or the corresponding version), and $arch (change to x86_64 or whatever needed). URLs obtained in the RH server are very long and this can be very easily overlooked (it took my a long while to spot the problem).

Last but not least, maybe another mention about where to check about the sync status (/var/log/rhn/reposync) when it's selected to sync the channel from the web-UI (I'm sure it must be mentioned in other place(s) of the docu itself, but a reminder would be nice).

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?
MC, Can, Don...

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

If anything is approved, it'd go to any running version, 4.1 and 4.2

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by raulosuna** [comment]
An addition (or correction) to this:

the important field to uncheck (checked by default) is within the repository configuration and it's called "Has signed metadata?". This is correctly explained in the documentation, but it simply gets lost in a big amount of data and customers simply don't see it. Please stress this part, as at least till now, this field is checked by default and needs to be manually unchecked.

Thanks in advance!

**Comment by keichwa** [comment]
Raul, I need more information, please.  Where exactly is it missing? It would be very helpful if you could cut-and-paste the html filename and the section title.  Thank you for your feedback!

**Comment by keichwa** [comment]
To me this looks fixed as part of https://github.com/SUSE/spacewalk/issues/17044.
Please re-open if something still is missing!  Thanks for your help!
