### ISSUE TITLE
L10n of 4.2.x documentation - CJK PDFs for the Client Configuration Guide - missing section – “Supported SLE Micro and openSUSE MicroOS Client Features”, due to conditional text settings in NAV file. 

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1304]
**Description:** The section “Supported SLE Micro and openSUSE MicroOS Client Features” is missing from the localised version of the Client Configuration Guide, in Chinese, Japanese and Korean (CJK). This is due to different conditional text settings in the file ‘modules/client-configuration/nav-client-configuration-guide.adoc’ and ‘translations/ja/modules/client-configuration/nav-client-configuration-guide.adoc’, see line 15 in the Japanese NAV file. 

![client-configuration_nav-client-configuration-guide adoc_conditional_text_(supported-features-sles-micro adoc)](https://user-images.githubusercontent.com/68334239/143291999-3f8dad0e-3e78-4734-a5db-e88f27cea65f.PNG)
(English on the left -- localised Japanese on the right.)

This NAV file is generated into the /translations/ directory. I don't know how this change is happening and where to edit to fix.

See here for currently published:
https://documentation.suse.com/suma/4.2/ja/pdf/suse_manager_client-configuration_guide.pdf
Page 12 of PDF (folio 8). The “Supported SLE Micro and openSUSE MicroOS Client Features” section is missing. It should precede the section you see there, "サポートされているAlmaLinuxの機能".
Compare with English:
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf
Page 14 of PDF (folio 10).

**Comment by jcayouette** [comment]
Great thanks! @ptinley-vt

**Comment by jcayouette** [comment]
Fixed! Thank you
