### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – missing section – “Registering SLE Micro Clients”, due to conditional text settings in NAV file. 

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1305]
**Description:** The section “Registering SLE Micro Clients” is missing from the localised version of the Client Configuration Guide, in Chinese, Japanese and Korean (CJK). This is due to different conditional text settings in the file ‘modules/client-configuration/nav-client-configuration-guide.adoc’ and ‘translations/ja/modules/client-configuration/nav-client-configuration-guide.adoc’, see line 51 in the Japanese NAV file. 

![client-configuration_nav-client-configuration-guide adoc_conditional_text_(clients-slemicro adoc)](https://user-images.githubusercontent.com/68334239/143294460-fa92f928-806e-4205-8641-bc94f95c2da6.PNG)
(English on the left -- localised Japanese on the right.)

This NAV file is generated into the /translations/ directory. I don't know how this change, or difference, is occurring and where to edit to fix.

See here for currently published:
https://documentation.suse.com/suma/4.2/ja/pdf/suse_manager_client-configuration_guide.pdf
Page 74 of PDF (folio 70). The missing section "Registering SLE Micro Clients", which is just over 2 pages of content, should precede the section "AlmaLinuxクライアントの登録".

Compare with English:
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf
Page 81 of PDF (folio 77).

**Comment by jcayouette** [comment]
Fixed, Thank you!
