### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – missing section – “Product Migration”, due to conditional text settings in NAV file.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1306]
**Description:** The section “Product Migration” is missing from the localised version of the Client Configuration Guide, in Chinese, Japanese and Korean (CJK). This is due to different conditional text settings in the file ‘modules/client-configuration/nav-client-configuration-guide.adoc’ and ‘translations/ja/modules/client-configuration/nav-client-configuration-guide.adoc’, see line 104 of the Japanese NAV file. 

![client-configuration_nav-client-configuration-guide adoc_conditional_text_(client-upgrades-product-migration adoc)](https://user-images.githubusercontent.com/68334239/143296921-e86563e0-dc7a-4dde-9e7a-321fae61daaa.PNG)
(English on the left -- localised Japanese on the right.)

This NAV file is generated into the /translations/ directory. I don't know how this change, or difference, is occurring and where to edit to fix.

See here for currently published:
https://documentation.suse.com/suma/4.2/ja/pdf/suse_manager_client-configuration_guide.pdf
Page 175 of PDF (folio 171). The missing section "Product Migration", which is just over 2 pages of content, should precede the section "仮想化". (Virtualization). (Top of the page).

Compare with English:
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf
Page 187 of PDF (folio 183).

**Comment by jcayouette** [comment]
Thanks! Looking into it.

**Comment by jcayouette** [comment]
Fixed. Thank you!
