### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – an image is too wide in the localised CJK books

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1307]
**Description:** The image appearing on page 139 of the English PDF of the Client Configuration Guide is too wide and does not fit on the page. 

Please edit the EN file at modules/client-configuration/pages/autoinst-pxeboot.adoc, line 16.
image::cobbler_menu.png[scalewidth-120%]

I suggest setting the scalewidth attribute to "[scalewidth-100%]".

![client-configuration_wide-image_cobble_menu(autoinst-pxeboot adoc)](https://user-images.githubusercontent.com/68334239/143299916-b764f582-8f0a-4fcd-97ed-00304145df5f.PNG)
_(Those dark grey vertical bars show the limits of the page, which is white, in the PDF viewer, and help illustrate that the image goes 'off the page'.)_

The image does not fit on the page in the EN book but at least it does not go off the page because it is centered. The image goes off the page into the margins in the localised books, and looks bad.

See here for currently published:
https://documentation.suse.com/suma/4.2/ja/pdf/suse_manager_client-configuration_guide.pdf
Page 128 of PDF (folio 124). 

Compare with English:
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf
Page 139 of PDF (folio 135).

**Comment by jcayouette** [comment]
Thanks, looking into it!

**Comment by jcayouette** [comment]
Fixed!
