### ISSUE TITLE
L10n of 4.2.x documentation – Client Configuration Guide – L10n QA found a possible source error – Corrupt list

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1308]
**Description:** It appears that the list on the top of PDF page 149 (folio 145)[1] is not formatting as intended. 
Please edit the EN file client-configuration/pages/autoinst-profiles.adoc to fix this.

The text renders as follows in the PDF:

![client-configuration_corrupt_list_formatting_src_error_(autoinst-profiles adoc)](https://user-images.githubusercontent.com/68334239/143301261-953bcc7f-7693-41b7-be00-8967b43e22a8.PNG)

But it looks like it was intended be an unordered list, when you look in the asciidoc file:

![client-configuration_corrupt_list_src-error_asciidoc_(autoinst-profiles adoc)](https://user-images.githubusercontent.com/68334239/143301263-281c83fa-3f12-44d5-85f7-a81eec7e21f1.PNG)

I think a blank line is required before a list in asciidoc.

[1] https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf

**Comment by jcayouette** [comment]
Right on thanks. Ill fix it!

**Comment by jcayouette** [comment]
Fixed. I found an additional error on the page in an ordered list and fixed this as well.
