### ISSUE TITLE
L10n of 4.2.4 documentation – Client Configuration Guide – L10n QA found a possible source error – Corrupt list in “registration-bootstrap.adoc”

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1311]
**Description:** _(This issue appears in the 4.2.4 book and is not published online yet, that I can see.)_ It appears that new text added in 4.2.4 branch, in the file 'registration-bootstrap.adoc' at line 155, is intended to be a list, but it does not format as such in the PDF page 69 (folio 65).
Please edit the EN file client-configuration/pages/registration-bootstrap.adoc at line 155 to fix this.
The text renders as follows in the PDF:
![client-configuration_corrupt_list_src-error_pdf_(registration-bootstrap adoc_ln155)](https://user-images.githubusercontent.com/68334239/143463056-c6d6d3cd-0d0b-4251-834d-2c747d7a98cd.PNG)

But it looks like it was intended be an ordered list, when you look in the asciidoc file:
![client-configuration_corrupt_list_src-error_asciidoc_(registration-bootstrap adoc_ln155)](https://user-images.githubusercontent.com/68334239/143463051-a8e9c057-7c06-4a0f-8045-2c3e0e2fa37b.PNG)

I think a blank line is required before a list in asciidoc.

**Comment by jcayouette** [comment]
Fixed thank you!
