### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Installation Guide – missing content. Table 10, page 17, corruption due to conditional text settings (ifeval). 

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1312]
**Description:** Table 10: Supported Client Systems, on page 17, is a 22 row, 4 column table in the English book. However, in all 3 localised languages (CJK) the table is truncated to just 2 rows.  The header row in EN is:

Operating System | Architecture | Traditional Clients | Salt Clients

The header row in the targets contain content from the normal body of the table which has been shifted up into the header row.

x86-64、aarch64 | x86-64、aarch64 | x86-64 x | 86-64

This is caused by different conditional text settings in the file modules/installation/pages/client-requirements.adoc. 
The ifeval conditional text is in a completely different part of the table in the English acsiidoc file

![installation-guide-corrupt_table10_ifeval_PDF_(client-requirements adoc_ln20)](https://user-images.githubusercontent.com/68334239/143488417-a05bbab3-272a-4683-af2b-275335365c2c.PNG)

The asciidoc text looks like this:
![installation-guide-corrupt_table10_ifeval_asciidoc_(client-requirements adoc_ln20)](https://user-images.githubusercontent.com/68334239/143488422-27056734-3ea9-41b0-81f6-80ac0e2cddb1.PNG)

For reference, see PDF page 16 (folio 14) of the S. Chinese:
https://documentation.suse.com/suma/4.2/zh_CN/pdf/suse_manager_installation_guide.pdf

Compare with the English PDF page 19 (folio 17 / 65):
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_installation_guide.pdf

**Comment by jcayouette** [comment]
Fixed, Thanks!
