### ISSUE TITLE
L10n of 4.2.x documentation – Installation Guide – A comment in an asciidoc file corrupts a list in the localised CJK PDF files

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1313]
**Description:** Asciidoc tagging around this list becomes corrupt in the localised files because the comment // or remark in the EN file does not make it into the localised asciidoc file. The comment is essentially removed by the translation process. This leads to 2 + signs on consecutive lines, which is misinterpreted and creates corruption. 

Comparing the PDF of the English file with the Korean PDF.
![installation-guide-corrupt_list_page30_comment-breaks-list_PDF_(install-proxy adoc_ln51)](https://user-images.githubusercontent.com/68334239/143490298-b6423fa9-5d25-4bc2-bc9f-698dff0f4d6c.PNG)

Notice in the asciidoc file the comment is present in the EN file (right side) but missing in the Korean file (left side):
![installation-guide-corrupt_list_page30_comment-breaks-list_asciidoc_(install-proxy adoc_ln51)](https://user-images.githubusercontent.com/68334239/143490349-334c2965-fd8d-4495-836d-6cceb8986245.PNG)

This creates the 2 consecutive plus signs (+) which breaks the list. 

Please comment out the first plus sign on line 50 in the English file, modules\installation\pages\install-proxy.adoc

For reference, see PDF pages 26 and 27 (folios 24 / 57 and 25 / 57) of the Korean:
https://documentation.suse.com/suma/4.2/ko/pdf/suse_manager_installation_guide.pdf
Compare with the English PDF page 31 (folio 29 / 65):
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_installation_guide.pdf

**Comment by jcayouette** [comment]
Fixed. Thank you this was definitely a poorly constructed list!
