### ISSUE TITLE
L10n of 4.2.4 documentation – Upgrade Guide – L10n QA found a possible source error – a piece of paragraph text appears to be formatted as a code block

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1314]
**Description:** It appears that text in list item 4, page 6 in the English Upgrade should be in paragraph format rather than a code block.

![upgrade-guide_paragraph_formatted_as_code_PDF_(server-z adoc_ln40+server-minor-upgrade-uyuni adoc_ln45)](https://user-images.githubusercontent.com/68334239/143492522-c445ce10-74de-4855-9320-cdcaaf9039c8.PNG)

Probably because the text is already in a code block, the [command] macro does not work and displays _as is_.

This text is found in two files; **server-z.adoc** and **server-minor-upgrade-uyuni.adoc**.
![upgrade-guide_paragraph_formatted_as_code_asciidoc_(server-z adoc_ln40+server-minor-upgrade-uyuni adoc_ln45)](https://user-images.githubusercontent.com/68334239/143492925-8e8d70f4-de6c-45cc-b1c5-82cf3b2210c6.PNG)
Only the **server-z.adoc** content is rendered in the SUMA PDF. 
I suggest also fixing the same issue in **server-minor-upgrade-uyuni.adoc**.

**Comment by jcayouette** [comment]
Fixed, pushing to master, manager-4.2 and our 4.2.4 release branch. Thanks!
