### ISSUE TITLE
explain architecture abbrevs (clients)

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni-docs#1325]
Joseph proposed:

> I realized I approved it but I wonder if we should just make a list below the table and use asterisks to define the terms?

It probably would make sense.  I'll create a separate issue for your proposal.  Check `modules/client-configuration/pages/supported-features.adoc`.

_Originally posted by @keichwa in https://github.com/uyuni-project/uyuni-docs/issues/1299#issuecomment-988074848_

**Comment by 0rnela** [comment]
CLosing the issue here, any outstanding tasks will be handled on the spacewalk board.
