### ISSUE TITLE
SLE Micro appears under "openSUSE client registration"

### ISSUE THREAD

**Issue by GeraldPfeifer** [uyuni-project/uyuni-docs#1386]
https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-slemicro.html#_add_software_channels
currently lists SLE Micro as subitem of "openSUSE client registration", as a sibling to openSUSE Leap.

It should be listed under "SUSE client registration".

## Subject Matter Expert (SME)

Daniel Rahn, Matthias Eckermann, Gerald Pfeifer (= I)

## Version

4.2

**Comment by 0rnela** [comment]
This issue can be closed, the PR has been merged.
