### ISSUE TITLE
Red Hat Client Registration 

### ISSUE THREAD

**Issue by mgonnelly** [uyuni-project/uyuni-docs#1428]
Both sections of the Redhat configuration - CDN and RHUI - are missing the same essential information about populating the base channel with the contents of the RHEL ISO.

https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-rh-cdn.html#_prepare_custom_repositories_and_channels

and

https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-rh-rhui.html#_prepare_custom_repositories_and_channels

I notice it doesn't even explicitly say to create the base channel - just implies it from Table 2. Perhaps there was a block of text that explained this and it somehow got lost. In any case, following the steps as written will result in an empty base channel and clients will then complain about this:

Error: Failed to download metadata for repo 'susemanager:rhel8-pool-x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

A customer following this section has no hope of success without the information about how to populate this channel.

**Comment by keichwa** [comment]
To me this looks fixed as part of https://github.com/SUSE/spacewalk/issues/17044.
Please re-open if something still is missing!  Thanks for your help!
