### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – 3 missing sections – due to conditional text settings in NAV file.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1429]
**Description:** Working on CJK PDF outputs for 4.2.5. I am seeing the same issues as reported in the following bugs, reappearing in this version, even though the issues were fixed by Joseph in Nov 2021.

"Supported SLE Micro and openSUSE MicroOS Client Features"
https://github.com/uyuni-project/uyuni-docs/issues/1304
"Registering SLE Micro Clients"
https://github.com/uyuni-project/uyuni-docs/issues/1305
“Product Migration”
https://github.com/uyuni-project/uyuni-docs/issues/1306 

Not sure whether to reopen those bugs or just address them as new issues.

Regards,
Pat

**Comment by keichwa** [comment]
Verified with the PDF of August 2023.
