### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – A nested list is not being formatted correctly in the localised books

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1432]
**Description:** See Section 22.3.3.1 in the translated PDFs, all languages.

What should be a bulleted list item (·), under a numbered list item (2), is not being picked up as a list item at all. The text remains part of the numbered list item paragraph.
It may be due to a missing empty line before the list, line 122, in vhm-caasp.adoc.

![image](https://user-images.githubusercontent.com/68334239/155000140-afa89ff0-4714-4c94-b4a1-edbaa16b5fa5.png)

Pat

**Comment by jcayouette** [comment]
File depricated. Closing.
