### ISSUE TITLE
L10n of 4.2.x documentation - Chinese language review request to translate the term "Traditional" in certain tables

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1440]
**Description:** The Chinese language review request to translate the term "Traditional" as it appears in certain tables.

![image](https://user-images.githubusercontent.com/68334239/155123086-d0e80c44-61b1-4136-aa79-e3567efde541.png)

In that context it is a variable, {trad}, in the Weblate / PO files.
I have tested adding ":trad: 传统" at the bottom of: 
	uyuni-docs\branding\locale\attributes-zh_CN.adoc 
and confirm that it worked.

I cannot edit that file permanently. Needs to be updated by SUSE.

Regards,
Patrick

**Comment by jcayouette** [comment]
Adding your suggestion to zh_CN locale.
