### ISSUE TITLE
L10n of 4.2.x documentation - Upgrade Guide - Chapter 2 is not getting created in the CJK PDFs. Some content missing and 1 chapter less. Conditional text (ifeval) issue. 

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1441]
**Description:** Upgrade Guide. Chapter 2 is not getting created in the CJK PDFs. 
Some content missing and and the book has one less chapter. 

It appears that the localised NAV file is defective. The conditional text (ifeval) settings differ greatly.

The result looks like this; 

- The chapter label and first section is missing from the localised books. 
- What is section 2.1 in the English Upgrade guide appears as section 1.4 in the localised books.

![image](https://user-images.githubusercontent.com/68334239/155125892-a38f3f7a-abe1-4452-844a-be7b91042907.png)

The difference in the NAV file looks like this:

![image](https://user-images.githubusercontent.com/68334239/155128549-943a8a7e-e7c3-4755-987e-60287ff10286.png)

rgds,
Pat

**Comment by jcayouette** [comment]
Fixed.
