### ISSUE TITLE
Wrong wording for Registering SUSE Linux Enterprise Server with Expanded Support Clients

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni-docs#1450]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

Change of wording is required to avoid confusion and contradiction in these instructions.

## What does the documentation say now?

The Expanded Support software channels provided by SUSE only provide updates to packages, they do not provide the packages themselves. To register Expanded Support clients, you need to create custom empty base and child channels on your SUSE Manager Server, then import the Red Hat or CentOS packages into the custom channels. You must obtain the initial packages directly from Red Hat or CentOS before you can apply the updates provided by the Expanded Support software channels.

## What change is required?

The Expanded Support software channels provided by SUSE only provide updates to packages, they do not provide the packages themselves. To register Expanded Support clients, you need to register the Expanded Support Product (outlined below) to create the necessary base channel, then import any required Red Hat or CentOS packages as custom child channels. You must obtain the initial packages directly from Red Hat or CentOS before you can apply the updates provided by the Expanded Support software channels.

## Subject Matter Expert (SME)

dvosburg@suse.com

## Version

Which version of the software is this feature/update expected to land in (if known)?
4.1 and following

Which version of the documentation must this feature/update land in (if known)?
4.1 and following

Does the content need to be backported to previous documentation versions (if known)?
No

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by jcayouette** [comment]
Closing as @keichwa has added fixes suggest for this issue. @dvosburg Let us know if you see this issue elsewhere!
