### ISSUE TITLE
Merge (uyuni-)proxy-setup.adoc

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni-docs#147]
On 2020-03-13 17:41, Julio González Gil wrote:
> juliogonzalez approved this pull request.
> 
> Current PR should work, but I strongly suggest deciding what to use in
> all places. Sometimes we have `{productname} Proxy`, sometimes
> `{susemgrproxy}` and sometimes only `Proxy` :-)

Yes, agreed. 
- [x] I can probably merge all this and
- [ ] then have it in one file only again.

_Originally posted by @keichwa in https://github.com/uyuni-project/uyuni-docs/pull/130#issuecomment-598819203_

**Comment by Loquacity** [comment]
This has been merged
