### ISSUE TITLE
Salt Guide section on Grains has confusing content about Modules

### ISSUE THREAD

**Issue by nbornstein** [uyuni-project/uyuni-docs#1479]
## Documentation Update Required

The Salt Guide contains a definition of Grains that includes confusing information on Modules.

## What does the documentation say now?

Grains provide information about the hardware of a client. This includes the operating system, IP addresses, network interfaces, and memory. When you run a Salt command any modules and functions are run locally from the system being called. Salt modules are stored on clients and the SUSE Manager Server within the /usr/lib/python*/site-packages/salt/ directory.

## What change is required?

What content needs to be added?
The information on Modules does not belong in the Grains definition, and the Modules definition already seems fairly complete so I don't think it needs to go there. 

## Subject Matter Expert (SME)

???

## Version

This content appears in the Salt Guide for both 4.1 and 4.2.

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by 0rnela** [comment]
Thank you @nbornstein, this has been addressed.
