### ISSUE TITLE
Client registration with salt bundle lacks example - complex CLI required

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni-docs#1481]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

Client registration with salt bundle - specifically converting salt minion to salt bundle - needs an example command

## What does the documentation say now?
Apply util.mgr_switch_to_venv_minion with mgr_purge_non_venv_salt set to True to remove salt-minion and with mgr_purge_non_venv_salt_files set to True to remove all the files related to salt-minion. This second step repeats the first step, and then removes the old configuration files and the now obsolete salt-minion package.

## What change is required?

Keep what is there, add an example

What content needs to be added?

Example command:
salt \* state.apply util.mgr_switch_to_venv_minion pillar='{"mgr_purge_non_venv_salt_files": True, "mgr_purge_non_venv_salt": True}'

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?
Victor Z.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
Thanks Don!
in the meantime, Victor updated the documentation accodringly.  Victor wrote:

I've put the example with this PR:
https://github.com/uyuni-project/uyuni-docs/pull/1458
And the example is already there:
https://github.com/uyuni-project/uyuni-docs/blob/master/modules/client-configuration/pages/contact-methods-saltbundle.adoc
