### ISSUE TITLE
Add note/sentence about adding Ubuntu 18.04 main and updates channels when using webUI

### ISSUE THREAD

**Issue by patex666** [uyuni-project/uyuni-docs#1502]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

This is related to below part of documentation:
https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-ubuntu-old.html#_add_software_channels

In this part customers see options to use webUI or CLI to add Ubuntu 18.04 channels. Those ones that choose webUI (Table 1), they don't notice, or expect that main and updates channels are also needed to be added via CLI.

## What does the documentation say now?

I'm ok with what documentation says now, no need for change there, only add a note or additional sentence.

## What change is required?

Add a sentence or note somewhere in Table 1 part of documentation, that even when using webUI to add Ubuntu 18.04 channels, you need to add ubuntu-1804-amd64-main and ubuntu-1804-amd64-main-updates channels using CLI. Point to Table 3. Ubuntu Channels - CLI

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?
no idea

## Version

Which version of the software is this feature/update expected to land in (if known)?
4.1 and newer versions
Which version of the documentation must this feature/update land in (if known)?
4.1 and newer versions
Does the content need to be backported to previous documentation versions (if known)?
no

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by 0rnela** [comment]
Thank you @patex666 for reporting, this will be taken acre of.
