### ISSUE TITLE
New Parameter in rhn.cfg to support config of smtp port, auth and ssl/tls

### ISSUE THREAD

**Issue by wombelix** [uyuni-project/uyuni-docs#1568]
Enable Authentication, define Username and Passwort, enable SSL or STARTLS via rhn.cfg

New parameter:
- java.smtp_port = integer (default: 25)
- java.smtp_auth = true/false (default: false)
- java.smtp_ssl = true/false (default: false)
- java.smtp_starttls = true/false (default: false)
- java.smtp_user = string (default: null)
- java.smtp_pass = string (default: null)

**Comment by keichwa** [comment]
It is in now and backported
