### ISSUE TITLE
Security updates against reported vulnerabilities in uyuni repositories

### ISSUE THREAD

**Issue by jpgrazi** [uyuni-project/uyuni-docs#1584]
Hello 
I follow the legal documentation to update uyuni to its latest packages version. Today I found that the repos configured in the uyuni master for the proxies to be updated are outdated. The documentation states to configure the following in the master server:
spacewalk-common-channels opensuse_leap15_3
opensuse_leap15_3-non-oss
opensuse_leap15_3-non-oss-updates
opensuse_leap15_3-updates
opensuse_leap15_3-backports-update
opensuse_leap15_3-sle-updates
opensuse_leap15_3-uyuni-client
uyuni-proxy-stable-leap-153

All the process was done as a minor update to the proxy that is supposed to update the packages to the right versions for uyuni to work correctly.... but I found that the packages in those repos don't solve many of the security vulnerabilities reported in our Rapid 7 system. In fact, the uyuni proxy is having one of the highest scores of all the Linux servers.
I enabled the OS repos configured in the server since its installation, and those really pull the right OS packages that solve the vulnerabilities... but I’m afraid that those packages won't work correctly with the uyuni proxy software.
Can you point me to the right repositories that have the security vulnerabilities solved and work with uyuni proxy software well?
..or can I continue doing the update as mentioned, with all the repos in the system enabled, without risk to break the uyuni proxy services?

Thanks in advance for your answer/guidance on this.

Jean.

**Comment by mcalmer** [comment]
Btw: we are working on a way to let `spacewalk-common-channels` configure a regular sync as well.

**Comment by 0rnela** [comment]
@jpgrazi -- any further comments before we close this issue?

**Comment by jpgrazi** [comment]
Is ok thanks.

Enviado desde Yahoo Mail para Android 
 
  El jue, 22 de dic. de 2022 a la(s) 9:04 a. m., Ornela ***@***.***> escribió:   


@jpgrazi -- any further comments before we close this issue?
