### ISSUE TITLE
L10n – CJK PDFs for the Client Configuration Guide – missing section – "7.3.1. Registering openSUSE Leap Clients", and subsections, due to conditional text settings in NAV file.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1612]
Missing section(s).
"7.3.1. Registering openSUSE Leap Clients", and subsections.
Approx. 2.5 pages

![image](https://user-images.githubusercontent.com/68334239/174801000-27c62753-3a9a-4f0f-b33c-a0fc9a3ca7c4.png)

Patrick

**Comment by keichwa** [comment]
`master` looks fine to me.  We'll need @jcayouette 's help.
