### ISSUE TITLE
Proxy requirements are missing

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-docs#1616]
Currently uyuni doc does not contains information about uyuni proxy requirement.

https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-install-requirements.html

## Documentation Update Required

Table with uyuni proxy requirements.

## Subject Matter Expert (SME)
@mbussolotto 

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
Thank you, it is merged!
