### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – Numbered list item being corrupted - not picking up list item number 2.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1617]
**Description:** A numbered list is not being formatted correctly. List item 2 is missing.
**Location:** client-configuration/pages/contact-methods-saltbundle.adoc
I am not sure why the dot (.) that should trigger the creation of the list item is being lost in the translated files.
See English beside Japanese PDFs
![image](https://user-images.githubusercontent.com/68334239/174843211-4275cbbe-f79e-4254-8faa-7437780c8420.png)
Note list-item 2 is missing on Japanese. (Also missing in Chinese and Korean).

The English adoc looks like this:
![image](https://user-images.githubusercontent.com/68334239/174843723-310ce443-8a3c-4ad1-be5d-714fca2b9e95.png)

The Japanese adoc looks like this:
![image](https://user-images.githubusercontent.com/68334239/174844810-1c5ca4a3-74fa-463e-84f1-038ab419aa60.png)
Note, there is no dot (.) in the Japanese file.

The PO file looks like this:
![image](https://user-images.githubusercontent.com/68334239/174845236-d8ccc7e8-4d98-4ca0-8131-693e11718965.png)

The dot is not included in the segment for translation - neither the source nor the target. It is external to translation.

Not sure how to fix this.

regards,
Patrick

**Comment by keichwa** [comment]
adoc markup seems to be correct.  We'll need @jcayouette 's help.

**Comment by jcayouette** [comment]
The adoc markup is incorrect.

 A concat `+` must be used after **each** block element. In the incorrect example above we use a list block followed by a code block. We do not follow up the code block with a + so the following sentence breaks the list.

**Comment by jcayouette** [comment]
Incorrect list markup. An additional continuation `+` was needed. 

See: https://github.com/uyuni-project/uyuni-docs/tree/manager-4.2-translation-fixes-jcayouette
