### ISSUE TITLE
L10n of 4.2.x documentation – CJK PDFs for the Client Configuration Guide – Broken numbered lists in the autoinst-profiles.adoc

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1619]
**Description:** Two numbered lists are not being formatted correctly. Dropping numbers and restarting at zero.
**Location:** client-configuration/pages/autoinst-profiles.adoc
See the English beside Chinese PDFs
![image](https://user-images.githubusercontent.com/68334239/174855036-1c41b4e3-ecf2-483a-832f-6c2d2737ba16.png)

The English adoc file looks like this:
![image](https://user-images.githubusercontent.com/68334239/174855586-2c513af0-921a-413a-a88b-01dfa011f7a4.png)
The Chinese adoc file looks like this:
![image](https://user-images.githubusercontent.com/68334239/174861105-2ada0199-ce05-4cc2-b5b7-add731a8667c.png)

The same happens with the Japanese and Korean - the dot (.) is lost.

Similarly, in the next Procedure, that list is broken and 2 numbers are dropped and the list is subsequently restarted:
![image](https://user-images.githubusercontent.com/68334239/174861701-0a68f692-8bc1-42b2-8753-40d849cb3289.png)

Pat

**Comment by jcayouette** [comment]
Fixed in manager-4.2
