### ISSUE TITLE
An unnecessary + (plus) is displaying in a Warning in the Client Configuration Guide. 

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1624]
**Description**: An unnecessary + (plus) in displaying in a Note in the Client Configuration Guide. 
**Location**: client-configuration/pages/clients-slemicro.adoc, Line: 31

Please remove. I cannot commit my local changed file to GH.

![image](https://user-images.githubusercontent.com/68334239/175071450-bcc77790-2b44-43f7-8272-0273fd88dd4a.png)

**Comment by keichwa** [comment]
fixed locally
