### ISSUE TITLE
Client Configuration Guide - section numbering is missing on the title 'Registering SLE Micro Clients'.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1626]
**Description:** The section numbering is missing on the title **Registering SLE Micro Clients** in Client Configuration Guide. It should be 7.2.2.
**Location:** client-configuration/pages/clients-slemicro.adoc, Line: 1

![image](https://user-images.githubusercontent.com/68334239/175076140-db487f41-8470-4fea-8f15-a929c25de839.png)

This is caused by a missing opening square bracket.
![image](https://user-images.githubusercontent.com/68334239/175077821-a3726a1f-05dd-4f09-aac2-2b79ac5611b2.png)

I cannot commit my changed local file. (do not have permissions)

**Comment by keichwa** [comment]
already fixed in `master`.  I do not know whether we must backport this fix to some other branch. @jcayouette ?
