### ISSUE TITLE
Documentation doesn't clearly explain how to create a custom salt state.

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#1634]
https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/salt/salt-custom-states.html
(applies to the similar url for Uyuni).

Following the procedure didn't allow to run a custom salt state.

**Comment by vzhestkov** [comment]
Not sure if I understand right what you mean. What did you try to do?

**Comment by keichwa** [comment]
Can one of you provide positive feedback? @raulillo82 or @vzhestkov .

**Comment by vzhestkov** [comment]
For me it was not clear what was the problem @raulillo82 found, I would check first what was the error. The documentation section looks fine for me, but the customers always complain that it's not clear what should they write as a state. Not sure how to give the proper answer for it: any valid state will work :-)

**Comment by raulillo82** [comment]
I'm afraid I can't follow up on this, should I have something more detailed about this, I'll come back but meanwhile feel free to close it.
