### ISSUE TITLE
Salt bundle documentation improvement

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#1644]
## Documentation Update Required

Information is too brief for 4.2, version that does not use the salt bundle by default. If someone wants to enable it, they'll need at least the mgr-create-bootstrap command (even if that can be guessed from the help). Some more clarifications could be added. I think the docu was written mainly with 4.3 & uyuni in mind, where everything's working by default.

## What does the documentation say now?

See https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/contact-methods-saltbundle.html

## What change is required?

Some details specific to enabling the bundle in 4.2, with exact commands.

## Subject Matter Expert (SME)

For the time being I'll be doing this myself, but of course it'll need reviewing when submitted.

## Version

Which version of the software is this feature/update expected to land in (if known)? It's already in 4.2.7. Default in 4.3.X & uyuni.
Which version of the documentation must this feature/update land in (if known)? 4.2. I don't know if it makes sense for any other version. In 4.1 the bundle is not supported.
Does the content need to be backported to previous documentation versions (if known)? Not to 4.1. And I believe it won't make sense in 4.3.

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
It is merged.
