### ISSUE TITLE
Add Rocky Linux 9 Documentation

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni-docs#1661]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

As mentioned in [uyuni#5682](https://github.com/uyuni-project/uyuni/pull/5682) it is needed to add documentation for Rocky Linux 9.

## What does the documentation say now?

It only mentions version 8, but not 9 up to now.

## What change is required?

It is most likely nearly the same documentation that's needed, there are no module streams up to now, but they will most likely come with 9.1 so it's really the same documentation as for 8.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

I think `2022.07` or `2022.08`, it's a new feature so no backporting needed.

Thank you very much!
If needed I can also update the docs myself and send a PR 👍🏻

**Comment by keichwa** [comment]
Thank you for the proposal!  Is it you how is already working on it?

**Comment by lumarel** [comment]
I at least promised to work on these docs 🙂
Yeah I will see that I will have a first draft until next week!

**Comment by keichwa** [comment]
Lukas Magauer ***@***.***> writes:

> I at least promised to work on these docs 🙂
> Yeah I will see that I will have a first draft until next week!

Fine, thanks for the info update!

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)
