### ISSUE TITLE
Support for CentOS 8 ended upstream yet we still list it as supported

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni-docs#1700]
Our practice for other linux distros is to end support when the upstream vendor does.  Thus we need to remove CentOS8 from the supported list, as support ended December 31, 2021.

**Comment by juliogonzalez** [comment]
Ah, no, this is Uyuni. Ignore my comment ;-)

**Comment by keichwa** [comment]
Thanks, Don, for the notification!  All active branches adjusted accordingly!
