### ISSUE TITLE
Make Introductions consistent across left nav

### ISSUE THREAD

**Issue by jcayouette** [uyuni-project/uyuni-docs#171]
Preference for menu behavior should be to go to intro page when clicked and not expanded to display the intro below.

For example (**CORRECT**): 
```
* xref:client-config-overview.adoc[Client Configuration Guide]
** xref:supported-features.adoc[Supported Clients and Features]
*** xref:supported-features-sles.adoc[SLES Supported Features]
```

In the above the first level list item points to the client overview "introduction".

In this example... we only use a text string (**INCORRECT**): 
```
* Installation Guide
** xref:install-intro.adoc[Introduction]
** Requirements
```

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/11179
