### ISSUE TITLE
Typo OpenSCAP Section 2 

### ISSUE THREAD

**Issue by pmullin99** [uyuni-project/uyuni-docs#1710]
2. Prepare Clients for an SCAP Scan (https://documentation.suse.com/suma/4.3/en/suse-manager/administration/openscap.html#_prepare_clients_for_an_scap_scan)

In the Important section there is a duplicate SUSE:
For Non-SUSE OSs, note that the included profiles are community supplied and not officially supported by SUSESUSE.

**Comment by keichwa** [comment]
fixed and backported.
