### ISSUE TITLE
SUMA Disconnected Setup and Mandatory SUMA Client Tools Channels

### ISSUE THREAD

**Issue by slsnow** [uyuni-project/uyuni-docs#1723]
## Documentation Update Required

When running a disconnected Setup with SMT or RMT, the SUSE Manager Tools Channels must be added, or else the corresponding products will not be detected. This is not mentioned in the documentation.

For example, if you do not add the "sle-manager-tools/12/x86_64" product, then when you add the normal SLES 12 channels, even if mirrored and passed exported to SUMA properly, those products will not be pulled into SUSE Manager and syncronizable channels (mgr-sync will not be able to add the product).

## What does the documentation say now?

The documentation currently does not mention these mandatory channels:
https://documentation.suse.com/suma/4.3/en/suse-manager/administration/disconnected-setup.html#_synchronize_rmt

## What change is required?

At the very least this should be mentioned.

Here is potentially what we could say:

---

## Changes

(Currently there are 3 Sections, I could see this section being squished between section 2 and 3 on that page, or perhaps as part of the RMT or SMT instructions).

- 3. Mandatory Channels

The corresponding SUSE Manager Client Tools Channels are required, in order for SUSE Manager to be able to sync a given channel.
If these channels are Not enabled, SUSE Manager may fail to detect that product altogether.

Run the following to enable these mandatory channels:

SLES 12 -
RMT: `rmt-cli products enable sle-manager-tools/12/x86_64` 
SMT: `smt repos -p sle-manager-tools,12,x86_64`

SLES 15 -
RMT: `rmt-cli products enable sle-manager-tools/15/x86_64`
SMT: `smt repos -p sle-manager-tools,15,x86_64`

Then mirror the channels, and export.

Other distributions, or architectures, can be enabled. For more details on enabling product channels or repositories to be mirrored, see the documentation:
RMT: https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-rmt-mirroring.html#sec-rmt-mirroring-enable-disable
SMT: https://documentation.suse.com/sles/12-SP5/single-html/SLES-smt/index.html#smt-mirroring-manage-domirror

---

## Subject Matter Expert (SME)

I know this process pretty well, and will create a documentation bug as well in bugzilla to track this. Would love any of the developers to validate as well. 

## Version

Uyuni
SUMA 4.2, 4.3

Should be included in this documentation and future documentation.

## Internal SUSE Reporters

Will link the bug, but this doesn't need to be kept confidential.

**Comment by slsnow** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1202464

**Comment by keichwa** [comment]
Samuel, thanks for the detailed information!  Can you please review https://github.com/uyuni-project/uyuni-docs/pull/1736 ?  There I also uploaded a PDF with the updated Disconnected Setup chapter.

**Comment by keichwa** [comment]
I now also have the 4.3 and 4.2 backport:

* https://github.com/uyuni-project/uyuni-docs/pull/1739
* https://github.com/uyuni-project/uyuni-docs/pull/1738

**Comment by keichwa** [comment]
all is merged now --thanks for all your help!
