### ISSUE TITLE
Wrong abbreviation and explanation for openscap

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#1726]
## Documentation Update Required
https://documentation.suse.com/suma/4.3/en/suse-manager/reference/audit/openscap-menu.html or ./modules/reference/pages/audit/openscap-menu.adoc

This page has an inaccurate description according to a customer.

## What does the documentation say now?

"The Security Certification and Authorization Package (SCAP) is a standardized compliance checking solution for enterprise-level Linux infrastructures. "

## What change is required?

It should rather say:
"The Security Content Automation Protocol (SCAP) is a synthesis of interoperable specifications derived from community ideas. (*1, *2)

The objective are applications and different OS (*3), not only GNU/Linux.

*1) https://csrc.nist.gov/projects/security-content-automation-protocol 
*2)  https://www.open-scap.org/features/standards/
*3) https://ncp.nist.gov/repository?scap

Should the change be accepted, there are other pages whose references to OpenSCAP should be corrected, I will track this accordingly in the PRs.

## Subject Matter Expert (SME)

Please have this reviewed by the SUSE Manager team, I would ask to delegate it to PMs and they can let the appropiate person review. Till the changes are ready please assign the issue to myself.
I'm preparing the changes and will send PRs for all 4 versions myself.

## Version

Which version of the software is this feature/update expected to land in (if known)? All supported versions: 4.1, 4.2, 4.3 and Uyuni.
Which version of the documentation must this feature/update land in (if known)? See previous point.
Does the content need to be backported to previous documentation versions (if known)? I would say that it makes sense not to change anything for unsupported versions.

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

Not applicable

**Comment by keichwa** [comment]
Thanks!  Yes, but better wait with backports until master is approved :)  I proposed some small changes.
