### ISSUE TITLE
Add specifics on what's supported for monitoring formulas and exporters

### ISSUE THREAD

**Issue by slsnow** [uyuni-project/uyuni-docs#1759]
## Documentation Update Required

https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/monitoring.html
https://documentation.suse.com/suma/4.3/en/suse-manager/administration/monitoring.html

This was discussed in an internal chat. The documentation could be more specific on which systems are supported for the prometheus and grafana formula, and also which exporters are supported, and which are not. 

## What does the documentation say now?
At the top it says:
>Prometheus and Grafana packages are included in the SUSE Manager Client Tools for:
>
>- SUSE Linux Enterprise 12
>- SUSE Linux Enterprise 15
>- openSUSE Leap 15.x

...
Later, in section 3.2 Monitoring Managed Systems it says:
>These exporters can be installed on managed systems:

## What change is required?

It would be nice if it clearly stated something like...
"The Prometheus and Grafana packages are included in the SUSE Manager Client Tools, **and only supported**, for:"
Or perhaps a warning stating that it's only supported for those systems that include the packages in the SUSE Manager Client Tools, however it would be best to word that.

...
It was mentioned that currently exporters only work for SLES, opensuse, Redhat, Debian/Ubuntu. It doesn't seem that it is supported for other third party clients yet (that could be a separate enhancement, but the docs should probably reflect what is currently supported).

## Subject Matter Expert (SME)

Witold Bedyk

## Version

SUMA 4.2 and 4.3

**Comment by keichwa** [comment]
Thank you for the report.  I'll ask development for more info.

**Comment by keichwa** [comment]
merged and backported.
