### ISSUE TITLE
The mgr-bootstrap script

### ISSUE THREAD

**Issue by slsnow** [uyuni-project/uyuni-docs#1822]
## Documentation Update Required

SUSE Manager's best tool for modifying a bootstrap script is the command "mgr-bootstrap". However, the documentation barely mentions the command.

## What does the documentation say now?

Particularly in this section of the docs:
https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/registration-bootstrap.html#modify.bootstrap.script

It recommends copying the default bootstrap script, and creating custom scripts. This method is okay, if you know what you're doing, but is also prone to error.

## What change is required?

From my experience, the best method for creating bootstrap scripts, is to use the mgr-bootstrap tool, and is better, and faster than manually editing the bootstrap script.

Something like the following could be a good addition to the current documentation:

"
The `mgr-bootstrap command` is a helpful CLI tool that generates custom bootstrap scripts to be used by SUSE Manager client systems for the purpose of simplifying their initial configuration.  

The arguments `--activation-keys=` and `--script=`, are typically the only mandatory arguments.

```
mgr-bootstrap --activation-key=<ACTIVATION_KEYS> --script=bootstrap-<EDITED NAME>.sh
```

The `mgr-bootstrap` tool includes several other options, including the ability to set a specific hostname, set specific gpg keys, and set the registration method (traditional, salt-minion, salt-bundle). 

For a more detailed view of available options, see "man mgr-bootstrap", or run "mgr-bootstrap --help".

## Subject Matter Expert (SME)

Silvio, or probably pretty much any developer.

## Version

4.2+

## Internal SUSE Reporters
Low priority, so I won't create a bugzilla report for this.

Thanks.

**Comment by keichwa** [comment]
Done and backported to 4.3.  Thank you for the issue report!
