### ISSUE TITLE
Reboot on SLE-Micro - characteristics and limitations

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-docs#1843]
Testing action chains on SLE Micro, I found out some behavior that should be documented. Some of this info are not applicable just to action chain but in general at all actions to transactional update.

## Documentation Update Required

- In an action chains, system reboots only if there are changes in the snapshot.  E.g. an action chain with just a reboot would not work

- Reboot inside a Salt Remote command would not work, since all the commands are executed inside a snapshot 

- Reboot command is managed by transactional update configuration, so it means that it may not be applied instantly (e.g. if configuration is rebootmgr with "default" method, system is reboot during maintenance window)

## Subject Matter Expert (SME)

@mbussolotto 

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by mbussolotto** [comment]
CC @wweellddeerr , probably you noticed something else that can be documented.

**Comment by keichwa** [comment]
AFAICS, this is the only statement about rebooting SLE Micro
(clients-slemicro.adoc):

> They do not affect a running system as no changes are activated until after the system is rebooted.

Thus we first need a statement how Uyuni and SUMA can reboot SLE Micro.
Then we can warn about things that are not enough to cause a system
reboot.

Additional there is probably a general statement about rebooting in the
Reference guide where we could add warnings.  Or what exactly do you
have in mind?

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)

**Comment by mbussolotto** [comment]
> > They do not affect a running system as no changes are activated until after the system is rebooted.

> Thus we first need a statement how Uyuni and SUMA can reboot SLE Micro. Then we can warn about things that are not enough to cause a system reboot. 

Yes, agree. Just remind that the same should also be added to Micro OS section.

> Additional there is probably a general statement about rebooting in the Reference guide where we could add warnings. Or what exactly do you have in mind?

In general, since  transactional update minions have some limitations on Action Chains and Reboot command, I would expect that this limitations are mentioned here https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/actions.html , but I'm not sure which is the best way to do.  

Just an idea:
-  https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/actions.html#_action_chains, a warning like `For transactional update systems, please consider that an action chain is executed inside a single snapshot, until there's a reboot action. This can cause some limitations.` and a link to the section where reboot  (and warn) on SLE Micro is explained.
-  https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/actions.html#_remote_commands a warning like `For transactional update systems, please consider that a remote command is run inside a single snapshot. This can cause some limitations`, always with a link  to the section where reboot  (and warn) on SLE Micro is explained.

**Comment by keichwa** [comment]
thanks, it is merged and backported!

**Comment by keichwa** [comment]
Thanks for your followup!

> Do you think it is OK to reopen this issue for these changes or should I create a new issue?

Maybe, it would be best if you'd click the "more dots `...`" in header line of your msg and then "Reference in new issue" to create a new one and link it back to this one at the same time.
