### ISSUE TITLE
Changes to schedule product migration in spacecmd

### ISSUE THREAD

**Issue by wweellddeerr** [uyuni-project/uyuni-docs#1859]
There is a pull request including two new options when [scheduling product migrations via spacecmd](https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/client-upgrades-product-migration.html#_product_mass_migration). The first option is to be used when the user wants to allow vendor change and its syntax is  `--allow-vendor-change` or, in the short version, `-v`. The second option is to be used when the user wants to remove products without successor in the target and its syntax is `--remove-products-without-successor` or, in the short version, `-r`.

The instructions regarding the `MIGRATION_TARGET` parameter should also be complemented to instruct the user to put the parameter value inside quotation marks: `"[190,203,195,1242]"`. This instruction is necessary because the brackets are used as wildcards in shell, and passing it without the quotation marks can cause problems in some scenarios.

**Comment by keichwa** [comment]
merged and backported.
