### ISSUE TITLE
Traditional and Salt Push via SSH (tunnel) clarifications.

### ISSUE THREAD

**Issue by slsnow** [uyuni-project/uyuni-docs#1961]
## Documentation Update Required

Note: I know this is a lot, and you may want to split this into more manageable separate issues. However, I wanted to include this at least in the beginning all together, since this is all connected to the same topic and processes.

---

The salt-ssh and push via ssh client management documentation is a bit confusing for users. This is understable, as it is not an easy task to document all of this clearly.

The points to be clarified will be detailed below. 

Category A: salt-ssh  
1 - salt-ssh (this is its own topic)

Category C: Contact Methods (salt)
2 - Salt Minion Methods (normal and bundle)
3 - salt push via ssh
4 - salt push via ssh tunnel

Category B: Contact Methods (traditional)
5 - Normal Traditional Contact Methods (rhnsd and osad)
6 - push via ssh
7 - push via ssh tunnel 

### Salt SSH
Doc Link: https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/salt/salt-ssh.html

- This does a great job of covering the salt-ssh options, but I think there could be a few improvements
- Sections to clarify
	- "1. SSH Connection Methods"
		- I think for clarity, it would be best if this section linked to the seperate contact method page (see below for more details)
		- The reasoning is that customers are searching the docs, find this page, and think this is all the information needed for the contact method push via ssh (salt) tunnel.
	- "5. HTTP Redirection"
		- For the same reasoning as above, this could be linked to the push via ssh (salt) page.
		- This information isn't included on that other page, and sometimes customers only find the other page. They aren't aware of how to configure the tunnel unless they are able to interpret both pages properly. Basically, unless they find both of these pages, and can read our minds a little, they cannot successfully complete this process without opening a support case.
- I don't have much else to complain about. For salt-ssh information, this page is put together very well.

### Client Management Methods
Doc Link: https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-intro.html

This is basically an overview page (seems like a carryover from the traditional days mostly). In my opinion, the purpose of this page should be to help customers decide and quickly find the information for the contact method they'd wish to use.

It would be nice if this section had a table, and maybe some bullte points to explain the differences in contact methods. Perhaps something like this:

| Method      | Type                     | Required External Inbound Ports | Description                                                 |
| ----------- | ------------------------ | ------------------------------- | ----------------------------------------------------------- |
| Salt        | minion (or salt bundle)  | 80, 443, 4505, 4506             | The default and recommended contact method.                                                  |
| Salt        | salt push via ssh        | 22, 80, 443                     | Useful if you'd prefer not to have an agent installed on the client system. | 
| Salt        | salt push via ssh (tunnel) | 22                              | Useful if a client is located in the DMZ, or otherwise has port access to SUSE Manager.                                                            |
| Traditional | rhnsd                    | 80, 443                         | Deprecated                                                            |
| Traditional | rhnsd + osad             | 80, 443, 5222                   | Deprecated                                                            |
| Traditional | push via ssh             | 22, 80, 443                     | Deprecated                                                            |
| Traditional | push via ssh (tunnel)      | 22                              | Deprecated                                                            |

We could just leave the traditional methods off the table all together, and mention that those methods are deprecated, but perhaps leaving it does add some clarity to the avaialble methods. I think the info is accurate, but we'll want to double-check with an SME.

Description on this page: I think it would be preferable to mention the default method, list the other methods in a bullet point list with links to their respective pages.

Perhaps something like this:

```
There are a number of ways that the SUSE Manager Server can communicate with clients. Which method you use depends on the type of client, and your network architecture.

By default, when a client is registered to SUSE Manager, the salt-minion agent is installed on the client system. This is the recommended contact method for most situations.

Push via Salt SSH Tunnel is often used in environments where clients have a limited connection to SUSE Manager. For example, in a DMZ network scenario. 

Traditional methods are considered deprecated.

Client Management Methods
- Salt Minion
- Push via SSH
- Traditional Contact Methods
```

### Contact Methods - Push via SSH (salt)
Doc Link: https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-saltssh.html

- Mentioned above in the Salt SSH section, it would be nice if the information from the salt-ssh page were included here, or preferably only here (with a link on the other page).
- We should include specific instructions for registration with both of these methods right here (Push via SSH and Push via SSH Tunnel).
	- The table of contents should be updated as well.
- It would be great to clarify the difference between normal push via salt and push via salt tunnel. I'm not sure that a new page is required, but it should be clearly defined.
	- Ports
		- Difference between tunnel and non tunnel push via ssh
	- Usage 
		- It should be made clear when they might want to use push via ssh, or with tunnel as well
	- Limitations
		- I have seen a customer wanting to use push via ssh just to be more similar to ansible, they didn't want to have an agent, but he didn't understand many of the limitations.
		- We should explain the perfomance and scaling benefits of salt-minion, as well as the limitations of push via ssh with or without using the tunnel method. 
		- Limitations could include:
			- Not sure which 3rd party distros we support with this
			- Performance hits, and scaling if you have a large deployment
			- Can't manually run package management from client in a tunnel situation
			- Other limitations
			- CLI instructions or limitations for bootstrapping, and other operations

### Contact Methods - Push via SSH (traditional)
Doc Link: https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/contact-methods-pushssh.html

The difference between when to use ssh-push and ssh-push tunnel, and other differences about the two aren't very clear on this page. 

## Subject Matter Expert (SME)

I added some information here, but I'd prefer a developer to give more insight on their thoughts, and to help clarify these sections.

## Version

SUMA 4.3 and SUMA 4.2. The information between the two might be a little different relating to traditional clients, and if the salt bundle is mentioned.

## Internal SUSE Reporters

An internal bugzilla report will be filed as well for tracking.

**Comment by slsnow** [comment]
Bug 1206461

**Comment by 0rnela** [comment]
> 1206461

https://bugzilla.suse.com/show_bug.cgi?id=1206461

**Comment by 0rnela** [comment]
Closing, because the corresponding bug has already been closed.
