### ISSUE TITLE
Wrong Scheduler Recommended in Large Deployment 

### ISSUE THREAD

**Issue by pmullin99** [uyuni-project/uyuni-docs#1968]
## Documentation Update Required
The wrong scheduler recommended in large deployment guide for SUSE Manager 4.3. 

## What does the documentation say now?
If the SUSE Manager Server is virtualized, enable the elevator=noop kernel command line option, for the best input/output performance. You can check the current status with cat /sys/block/<DEVICE>/queue/scheduler. This command will display a list of available schedulers with the currently active one in brackets. To change the scheduler before a reboot, use echo noop > /sys/block/<DEVICE>/queue/scheduler.

## What change is required?
In 15sp4, noop is no longer an option.  The only valid options are:
cat /sys/block/sda/queue/scheduler
mq-deadline kyber [bfq] none

What content needs to be added?
change "noop" to "none"

## Version
Since SLES 15SP2 there was a transition from non-multiqueue schedulers (noop, cfq, deadline) to multiqueue schedulers (none, mq-deadline, bfq, kyber).
This should be backported to 4.1 to 4.2.

**Comment by 0rnela** [comment]
@pmullin99 - is this the change you had in mind (**_noop_** to **_none_** in thise two lines):

If the SUSE Manager Server is virtualized, enable the elevator=**none** kernel command line option, for the best input/output performance. You can check the current status with cat /sys/block/<DEVICE>/queue/scheduler. This command will display a list of available schedulers with the currently active one in brackets. To change the scheduler before a reboot, use echo **none** > /sys/block/<DEVICE>/queue/scheduler.

**Comment by pmullin99** [comment]
You may want to indicate device in path, ex.  cat /sys/block/<block device>/queue/scheduler.  Yes, every place noop appears.

**Comment by 0rnela** [comment]
Fixed. Closing the issue.
