### ISSUE TITLE
Overview legend mentioned in docs, but not evident on dashboard. Obsolete?

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni-docs#1969]
The Web Interface Documentation at:

https://{hostname}/docs/en/uyuni/installation-and-upgrade/webui-setup.html#_top_navigation_bar

Shows this;

![image](https://user-images.githubusercontent.com/4052275/208679761-190807ae-9db8-4b1c-931b-5d99506722fa.png)

However, there is no eye icon visible on 2022.12

![image](https://user-images.githubusercontent.com/4052275/208679849-ef7ab26d-34cd-4d36-b685-c379443b5f1a.png)

I've navigated around a few likely looking pages and it doesn't appear so it's either:

a) No longer displayed and the doc section can be removed for 'Overview Legend'
b) Only appears on certain pages, and the doc section expanded to explain this.

(I think "a" is more likely, but happy to be corrected)

Thanks

**Comment by keichwa** [comment]
While reviewing the bug I asked (https://github.com/uyuni-project/uyuni-docs/pull/1984):

> I'm wondering whether we lost this feature intentionally (from the report, it could also be a software bug).

**Comment by keichwa** [comment]
Checking the suma-refhead server, the feature is back.  Someone fixed the bug.

**Comment by keichwa** [comment]
We can close it here. naica works on a solution.
