### ISSUE TITLE
Add a section about reboot method in SLE micro / transactional systems

### ISSUE THREAD

**Issue by wweellddeerr** [uyuni-project/uyuni-docs#2003]
It is necessary to add a section about **reboot method** in SLE micro / transactional systems.

Basically, as `transactional-update` supports several reboot methods, we recommend to use `systemd` in systems managed by SUMA, and using other method can lead to undesired behavior.

By default, reboot method is set to `auto`, which means that `rebootmgrd` will be used to reboot the system according to the configured policies if the service is running, otherwise systemctl reboot will be called.

When bootstraping a `transactional-system` on Suma, `systemd` will be configured as `REBOOT_METHOD`, if the system is in its default configuration. The idea behind this strategy is to put Suma on control of the reboot action, considering that `systemd` should perform the reboot immediately.

Otherwise, the only thing Suma will be able to do is to ask for a reboot and it will be managed in the peculiarities of each reboot method. Not having control of when the reboot should happen, also takes away from Suma the ability to perform the reboot on its own maintenance windows, which is not the ideal configuration.

The user must be able to change reboot method at any time and SUSE Manager will keep it. But in this case we should alert in the documentation that using any method different from `systemd` may cause undesired behavior.

**Comment by keichwa** [comment]
@wweellddeerr Thanks for the report and all the background info provided!  Nevertheless I've a question about:

> By default, reboot method is set to auto, which means that rebootmgrd will be used to reboot the system according to the configured policies if the service is running, otherwise systemctl reboot will be called.

- What are "configured policyies".
- "otherwise" probably means, if the user did not configure anything, `systemctl reboot` will be called.

Here I work on the PR: https://github.com/uyuni-project/uyuni-docs/pull/2234

**Comment by keichwa** [comment]
Thanks, @wweellddeerr I tried to make use of the info you provided.  See the related PR!

**Comment by keichwa** [comment]
Thanks for all your help.  It is now in master and a 4.3 backport is prepared.

**Comment by keichwa** [comment]
Done and backported to 4.3
