### ISSUE TITLE
Hyperlink to pdf file - 404 error

### ISSUE THREAD

**Issue by samoring** [uyuni-project/uyuni-docs#201]
When following:
https://www.uyuni-project.org/pages/stable-version.html

Selecting:
Upgrade Guide

Hyperlink:
server-update.pdf (page 19) results in 404 error.

**Comment by Loquacity** [comment]
Hi @samoring I'm having trouble locating the error, can you take a screenshot for me, maybe?

**Comment by Loquacity** [comment]
Unable to reproduce.
