### ISSUE TITLE
setDetails is missing description which values can be set for gpg_check

### ISSUE THREAD

**Issue by mmeiste** [uyuni-project/uyuni-docs#2015]
On the page:
https://documentation.suse.com/suma/4.3/api/suse-manager/api/channel.software.html#apidoc-channel_software-setDetails-2046578329

## Documentation Update Required

missing details which values can be set via gpg_check

## What does the documentation say now?

setDetails notes only:
"string "gpg_check" - enable/disable gpg check (optional)"

## What change is required?

looking at:
https://documentation.suse.com/suma/4.3/api/suse-manager/api/channel.software.html#apidoc-channel_software-create-1820295244
"boolean gpgCheck - true if the GPG check should be enabled by default, false otherwise"

So it's needs to be set to "true", otherwise it's counted as false.

## Version

SUSE Manager 4.3

**Comment by keichwa** [comment]
mc said:

> We use Boolean.parseBoolean() to convert the string into a boolean.
> That function expects "true" (case ignored) as value

@cbosdo shall we add such hints to the apidoc `faqs.txt`?  We could also start with a API docs section in our guides, if requested.

**Comment by keichwa** [comment]
I think I did my share.  Feel free to re-open if sth is missing.
