### ISSUE TITLE
replace standard SCAP profile by "stig" 

### ISSUE THREAD

**Issue by msmeissn** [uyuni-project/uyuni-docs#2017]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

in https://documentation.suse.com/suma/4.3/en/suse-manager/administration/openscap.html
replace xccdf_org.ssgproject.content_profile_standard by xccdf_org.ssgproject.content_profile_stig

as standard is not supported by us, by stig is the best support profile currently

## What does the documentation say now?

  Command-line arguments: --profile xccdf_org.ssgproject.content_profile_standard

## What change is required?

  Command-line arguments: --profile xccdf_org.ssgproject.content_profile_stig

What content needs to be added?
Include description of content, and potential location of new content in the docs suite.

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by Bischoff** [comment]
I think we use "standard" in the test suite as well :crying_cat_face:  Ping @orestis87 .

**Comment by orestis87** [comment]
yes we use the following:
`    And I enter "--profile standard" as "params"
    And I enter "/usr/share/xml/scap/ssg/content/ssg-sle15-ds-1.2.xml" as "path"
`

**Comment by keichwa** [comment]
Thanks for the report!  It's merged now (uyuni and 4.3).
