### ISSUE TITLE
Add openSUSE Leap 15.5 as a supported client

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#2028]
Add openSUSE Leap 15.5 as a supported client

## Documentation Update Required

Add openSUSE Leap 15.5 as a supported client

## What does the documentation say now?

Add openSUSE Leap 15.5 as a supported client

## What change is required?

What content needs to be added?
Include description of content, and potential location of new content in the docs suite.

## Subject Matter Expert (SME)
Anyone from the documentation team / susemanager documentation team.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Unconfirmed.
Which version of the documentation must this feature/update land in (if known)?
Unconfirmed.
Does the content need to be backported to previous documentation versions (if known)?
When enabled by SCC, it will be eventually backported to SUSE Manager 4.3.
Probably not any more to 4.2

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
I think we now can close this.  Documentation is merged.

**Comment by juliogonzalez** [comment]
@keichwa no, this can't be closed yet, see that backport to 4.3 is required, but not yet.

If you close it here, please open it at SUSE/spacewalk, so it can be added to https://github.com/SUSE/spacewalk/issues/20579

**Comment by keichwa** [comment]
Julio González Gil ***@***.***> writes:

> @keichwa no, this can't be closed yet, see that backport to 4.3 is
> required, but not yet.
>
> If you close it here, please open it at SUSE/spacewalk, so it can be
> added to https://github.com/SUSE/spacewalk/issues/20579

I added a new card to #20579

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)
