### ISSUE TITLE
Add SLE 15 SP5 as a supported client

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#2030]
Add SLE 15 SP5 as a supported client

## Documentation Update Required

Add SLE 15 SP5 as a supported client

## What does the documentation say now?

Short description of the documentation updated required.

## What change is required?

What content needs to be added?
Include description of content, and potential location of new content in the docs suite.

## Subject Matter Expert (SME)

Anyone from the documentation team / susemanager documentation team.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Unconfirmed.
Which version of the documentation must this feature/update land in (if known)?
Unconfirmed.
Does the content need to be backported to previous documentation versions (if known)?
When enabled by SCC, it will be eventually backported to SUSE Manager 4.3.
Probably not any more to 4.2

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
I think we now can close this.  Documentation is merged.
