### ISSUE TITLE
Formatting in registering opensuse clients superseeds right toolbar

### ISSUE THREAD

**Issue by raulillo82** [uyuni-project/uyuni-docs#2075]
As explained in subject. See screenshot.

- [x] Master
- [x] Manager-4.2
- [x] Manager-4.3

## Documentation Update Required

No content update, check this page of a recently built documentation: build/en/uyuni/client-configuration/clients-opensuseleap.html
Scroll down and one of the wide tables overrides the toolbar from the right.

## What does the documentation say now?

It's about the formatting. The new look is cool, but I found this problem when checking something else.

## What change is required?

What content needs to be added?
Include description of content, and potential location of new content in the docs suite.

## Subject Matter Expert (SME)

Documentation team.

## Version

I found this in Uyuni, but probably other SUSE Manager releases might be affected, such as 4.3

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by raulillo82** [comment]
Adding a screenshot, notice the top-right area:

![imagen](https://user-images.githubusercontent.com/17827278/218468461-a727e6d5-d1e4-4224-9455-2169aae98af1.png)

**Comment by beliefandreason-admin** [comment]
Thanks, Ill take a look!

**Comment by jcayouette** [comment]
Thanks, I will take a look!
