### ISSUE TITLE
How to freeze dmi info in hardware section?

### ISSUE THREAD

**Issue by yubazh** [uyuni-project/uyuni-docs#2168]
Hello! I did not know which category to create a question in, so I created it in an empty one. The question is how to make Uyuni keep DMI info and not update this section after adding a host? When adding a CentOS 7 host with venv-salt-minion, Uyuni updates hardware and fills in DMI info. After that, Uyuni periodically updates hardware on its own. The problem arises if, for some reason, the host becomes unavailable (breakdown, network unavailability) - in this case, the serial number information of the host contained in DMI info is reset. That is, it is impossible to find out the serial number of the crashed host. And this information is very necessary, especially in such moments. How can I make Uyuni stop updating DMI info either completely or at times of unavailability of venv-salt-minion? Keeping the last content of this section. 
I have tried to find answers to my questions in the documentation, however, searching for the word "DMI" does not yield any results.
If I have not searched well enough, could you please provide a link to an article that could help me? Is it possible to achieve this through the API? Alternatively, are there any workarounds?

**Comment by admd** [comment]
Hi @yubazh, after onboarding, Uyuni doesn't do automatic hardware refresh unless explicitly requested.

Besides that, DMI info is updated as part of hardware refresh. There is no way to exclude the DMI info update i-e if hardware refresh will be applied, DMI info will get updated.

**Comment by admd** [comment]
Ok scratch that. Above statement of not scheduling hardware refresh automatically is not correct anymore. We do schedule hardware refresh as part of new taskpmatic job `system-profile-refresh` but that happens only once a month.

**Comment by keichwa** [comment]
Thanks for your input.  It's merged, closing now.

**Comment by yubazh** [comment]
thank u guys!
