### ISSUE TITLE
Remove commented warnings in clients-* files

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni-docs#2272]
Remove some commented warnings in clients-* files in Client Configuration Guide:

[modules/client-configuration/pages/clients-oracle.adoc](https://github.com/uyuni-project/uyuni-docs/pull/2263/files/76ca689d8f2acbd584e65a6d308958cd2d3b0aa1#diff-b1a26ba89e11c726e9ca467ae5c8bcc4d943accd8903a5406162fd810ee44f5d): 
...
 //[WARNING]

Same in: [modules/client-configuration/pages/clients-rh-cdn.adoc](https://github.com/uyuni-project/uyuni-docs/pull/2263/files/76ca689d8f2acbd584e65a6d308958cd2d3b0aa1#diff-5f82cdb63577de2583f3f2f0ebd174f868855918a032c34aaaf3d5f69521f916)

_Originally posted by @juliogonzalez in https://github.com/uyuni-project/uyuni-docs/pull/2263#discussion_r1212735664_

**Comment by juliogonzalez** [comment]
The title does not describe the problem at all. Please fix it :-)

It's important to understand what this is about at the board.

And I'd also would write a proper description.

**Comment by keichwa** [comment]
yes, I'm lazy ;)  Consider it as a bookmark, but I'll fix it soon.

-- 
Karl Eichwalder                       SUSE Software Solutions Germany GmbH
                                      Frankenstraße 146, D-90461 Nürnberg
Geschäftsführer: Ivo Totev, Andrew Myers, Andrew McDonald, Boudien Moerman
(HRB 36809, AG Nürnberg)
