### ISSUE TITLE
Wrong Base OS Version on 4.3

### ISSUE THREAD

**Issue by pmullin99** [uyuni-project/uyuni-docs#2350]
## Documentation Update Required
Current 4.3 General requirements document says use 15SP5 when it should say 15SP4.
https://documentation.suse.com/suma/4.3/en/suse-manager/installation-and-upgrade/general-requirements.html

## What does the documentation say now?
SUSE Manager 4.3 is based on SLES 15 SP5 as the host operating system.
You do not require a separate code for SLES 15 SP5.
Direct link to SUSE Linux Enterprise 15 SP5, required to install SUSE Manager https://www.suse.com/download/suse-manager.  ## Points to SLES 15 SP4

## What change is required?
Change back to SP4

What content needs to be added?
SUSE Manager is not yet running on 15 SP5.

## Subject Matter Expert (SME)
SUMA PMs

**Comment by keichwa** [comment]
Yes, thanks for the report.  In the meantime it is fixed and published with the reverted version number.  Build or publication in the documents now is 2023-08-02.
