### ISSUE TITLE
Add documentation for custom channel sync checkboxes

### ISSUE THREAD

**Issue by r-richardson** [uyuni-project/uyuni-docs#2531]
## Documentation Update Required

The docs do not include any information about the optional checkboxes found in the webui for syncing channel repos.

![Screenshot from 2023-10-18 17-08-33](https://github.com/uyuni-project/uyuni-docs/assets/90002223/b7324438-c5f8-4e1e-a8a2-480408a7520b)

## What does the documentation say now?

Currently the optional checkboxes are not mentioned anywhere within the docs.

## What change is required?

There should be documentation on what the options do, and how they compare to the default sync behaviour.

**Comment by r-richardson** [comment]
It is also worth mentioning that these flags [will be saved persistently for each channel](https://github.com/uyuni-project/uyuni/pull/8319). Note that the "Sync now" button also saves the channel flags before performing the sync run.

![screen_buttons](https://github.com/uyuni-project/uyuni-docs/assets/90002223/6512c570-4ccd-40ad-9a87-bdb32ef01bfe)

**Comment by keichwa** [comment]
@r-richardson Hi Robert, if wanted you can review https://github.com/uyuni-project/uyuni-docs/pull/2896 now.
