### ISSUE TITLE
DOC: move all package files from /srv

### ISSUE THREAD

**Issue by mbussolotto** [uyuni-project/uyuni-docs#2543]
## Documentation Update Required
This PR https://github.com/uyuni-project/uyuni/pull/7651 would refactor current folder structure. We need to check how doc is affected. In general:

Configuration files, files generated at runtime remains where they are:

- /srv/www/htdocs/pub
- /srv/www/htdocs/pub/bootstrap
- /srv/www/htdocs/pub/repositories
- /srv/www/susemanager
- /srv/www/os-images
- /srv/www/tftpboot

Files owns by RPM are  moved to /usr/share folder:

- /usr/share/susemanager/www/tomcat
- /usr/share/susemanager/www/htdocs
- /usr/share/susemanager/www/htdocs/docs
- /usr/share/susemanager/www/pub/repositories/empty
- /usr/share/susemanager/www/pub/repositories/empty-deb
- /usr/share/susemanager/www/htdocs/help/eula.html
- /usr/share/susemanager/www/cgi-bin/

GPG key are now avaiable from (but Apache configuration guarantee retrocompatibility):

- FQDN/gpg

## Subject Matter Expert (SME)

@mbussolotto 

## Version

- [ ] Uyuni

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
I think we can consider it fixed now.
