### ISSUE TITLE
Install Uyuni Proxy with openSUSE Leap wrongly refers to  Leap 15.4

### ISSUE THREAD

**Issue by deneb-alpha** [uyuni-project/uyuni-docs#2563]
## Documentation Update Required

At https://www.uyuni-project.org/uyuni-docs/en/uyuni/quickstart/quickstart-install-uyuni-proxy.html 

The `Procedure: Mirroring Uyuni Proxy software` refers to Leap  15.4  but Uyuni is now based on Leap 15.5
![image](https://github.com/uyuni-project/uyuni-docs/assets/2315903/6ac1fd11-f43e-433d-8769-fbb857ae0458)

## What does the documentation say now?

The documentation should refer to Leap 15.5 

## What change is required?

The documentation should refer to Leap 15.5

## Subject Matter Expert (SME)

- 

## Version

Uyuni  needs  to  be fixed

**Comment by 0rnela** [comment]
Merged.
