### ISSUE TITLE
Custom salt formulas page references wrong file location

### ISSUE THREAD

**Issue by dvosburg** [uyuni-project/uyuni-docs#2605]
## Documentation Update Required

Custom salt formulas page references the wrong directory in one place and the right directory in another

## What does the documentation say now?

For example, the locale-formula states directory is located in:

/usr/share/salt-formulas/states/locale/

## What change is required?

It should say:

For example, the locale-formula states directory is located in:

/usr/share/susemanager/states/locale/

This would match what follows on the same page for the directory location of the correlating metadata, and the actual location of the files delivered in the rpm.

## Version

Problem found in the SUMA 4.3 docs here:
https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/salt/salt-formulas-custom.html

**Comment by keichwa** [comment]
Thanks Don!  The fix is merged and backported to 4.3 and Uyuni.
