### ISSUE TITLE
recommendation for worker_threads in the section specialized guides > Large Deployment Guide > Tunig Large Installations should be changed

### ISSUE THREAD

**Issue by thsnielsen** [uyuni-project/uyuni-docs#2705]
## Documentation Update Required
yes update required. The current advice could be damaging for large environments

https://documentation.suse.com/suma/4.3/en/suse-manager/specialized-guides/large-deployments/tuning.html#worker-threads

## What does the documentation say now?
Value recommendation 8-200
...
Example worker_threads: 50

Description of existing documentation.
Include screenshot if required.
![image](https://github.com/uyuni-project/uyuni-docs/assets/16719354/f08eb83b-7eef-446b-b279-6646ce7f87de)

## What change is required?
The recommendation should be lowered to f.ex.
Value recommendation 8-<max number of cpu's in the server -1>
...
Example worker_threads: 15

What content needs to be added?
nothing needs to be added

## Subject Matter Expert (SME)
Victor Zhestkov
see this presentation at 14min25sec  in : 
https://www.youtube.com/watch?v=dmuh4gfrEnQ&t=845s

## Version

- [x] 4.3
- [x] master - https://github.com/uyuni-project/uyuni-docs/pull/3155
- [x] 5.0

**Comment by mcalmer** [comment]
@0rnela this is important. Would be good if you could find a few minutes for this change

**Comment by keichwa** [comment]
merged and backported to 5.0 and 4.3.
