### ISSUE TITLE
Wrong Screenshot in docs "Reference / Images / Store"

### ISSUE THREAD

**Issue by bdekany** [uyuni-project/uyuni-docs#274]
Hi there,

In the docs Reference Book in Images / Store, there is a mismatched screenshot.
In "Create Store" Section there is a screen of "Create Profile".
https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/reference/images/images-stores.html

Reagrds

**Comment by Loquacity** [comment]
This has been resolved. Thanks for the bug report, and apologies for the tardy reply.
