### ISSUE TITLE
Customeer Case, how to replace customer certificate , rhn-ssl-tool --gen-server --rpm-only --dir /root/ssl-build/ didn’t create a proper format of server.pem that passes openssl verify.

### ISSUE THREAD

**Issue by asemen** [uyuni-project/uyuni-docs#275]
We have a customer, were customer complain Problem with replacing certificate in SUSE Manager
how to replace customer certificate.

He wrote the problem is resolved. Customer asked to update documentation https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/custom-ssl.html how to install a custom commercial certificate with intermediate CAs in the cert bundle.

Based on https://stackoverflow.com/questions/20409534/how-does-an-ssl-certificate-chain-bundle-work the proper order of certs in chain is important for openssl verify it properly. I discovered that command:

rhn-ssl-tool --gen-server --rpm-only --dir /root/ssl-build/

Didn’t create a proper format of server.pem that passes openssl verify. This is why customer ommited it in the steps and copied server.pem to  /etc/pki/spacewalk/jabberd directly manually. 
The second reason that Iz didn’t run the above command is that the format of server.crt for httpd is different than format of server.pem for spacewalk so he manually copied server.crt to  /etc/apache2/ssl.crt/ directory.
 
Could you please update documentation as customer asked? 
If better steps exist please modify them accordingly. 
It would be nice to verify why server.pem is not correctly build following openssl verify requirements when using command rhn-ssl-tool --gen-server --rpm-only --dir /root/ssl-build/. 

At this moment customer modified bootstrap script so that traditional client doesn’t install CA cert via rpm but by copying  RHN-ORG-TRUSTED-SSL-CERT file.

**Comment by Loquacity** [comment]
Thanks for this detailed report! We have significantly updated the documentation for SSL certs in the 4.1 release, and I believe this issue is now addressed. Please let us know if you come across any further issues.
