### ISSUE TITLE
Feedback from the field: unify suggested partitions

### ISSUE THREAD

**Issue by mbologna** [uyuni-project/uyuni-docs#284]
I got from the field a suggestion: unify suggested partition when installing Uyuni/SUSE Manager.

An example:

We start talking about "Partition permissions" https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/installation/general-requirements.html but the illustration of how to set up those partitions is illustrated later on only for public cloud: https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/installation/pubcloud-requirements.html#_separate_storage_volumes

IMHO I would unify everything into a general requirement:

- we require three different partitions
- we suggest using XFS as fstype for those partitions, backed by LVM
- only for public cloud: consider putting those partitions in a volume - not the root volume

Any suggestion welcome!

**Comment by Loquacity** [comment]
Absolutely agree, Michele. It's in the backlog.
