### ISSUE TITLE
azuremetadata cli incorrect

### ISSUE THREAD

**Issue by kbmetz** [uyuni-project/uyuni-docs#285]
Docs say 'azuremetadata --internal-ip' which returns an error

azuremetadata --privateIpAddress appears to return the correct internal IP

**Comment by Loquacity** [comment]
Thanks for this report, and apologies for my tardy reply. I'm not sure if I'm looking in the right place. I see that the documentation here https://www.uyuni-project.org/uyuni-docs/uyuni/installation/pubcloud-setup.html says to use `azuremetadata --instance-name`. Is this the command you are referring to?

Screenshot for reference:
![image](https://user-images.githubusercontent.com/3914967/88747727-b9bfb300-d192-11ea-909a-bd9341477f51.png)

**Comment by Loquacity** [comment]
Closing, as it seems to have been fixed in the meantime.
