### ISSUE TITLE
Instructions how to mirror Ubuntu ESM packages missing

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni-docs#2971]
With Ubuntu Pro, Canonical offers longer software maintenance for operating system components and several selected applications. Some users might want to distribute them using Uuyni.

## Documentation Update Required

Steps in order how to mirror the appropriate repositories are needed.

See the following write-up: https://cstan.io/en/post/2024/04/ubuntu-pro-mirror/

## What does the documentation say now?

Ubuntu ESM packages aren't mentioned at all.

## What change is required?

The well-known URLs can be documented. Also, the process of retrieving the users personal Ubuntu One bearer token and GPG keys needs to be clarified.

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
Thanks for report and PR.  It is merged now.
