### ISSUE TITLE
Package Management Verify subtab does not exist.

### ISSUE THREAD

**Issue by m0rbo** [uyuni-project/uyuni-docs#2973]
This page:
https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/package-management.html
Contains Step 1 "1. Verify Packages"
But there is no Verify subtab.
"In the SUSE Manager Web UI, navigate to Systems, click the client the package is installed on, and navigate to the Systems  Software  Packages  Verify subtab."
Does not exist in SUMA 4.3.11.

## Version
SUMA 4.3.11.

**Comment by keichwa** [comment]
Thanks for the report!  Verified also on 5.0.

**Comment by keichwa** [comment]
Backported to 5.0 and 4.3.
