### ISSUE TITLE
Typo in SUSE Manager documentation for PostgreSQL requirements

### ISSUE THREAD

**Issue by byuenhb** [uyuni-project/uyuni-docs#3053]
## Documentation Update Required

Typo in SUSE Manager documentation for PostgreSQL requirements
https://documentation.suse.com/suma/4.3/en/suse-manager/installation-and-upgrade/postgresql-requirements.html

## What does the documentation say now?

'15' instead of PostgreSQL. 
![WhatsApp 圖片2024-06-0511 42 38_bf590ca7](https://github.com/uyuni-project/uyuni-docs/assets/57099924/9d3ce9f7-eaad-48e3-9f13-7ae67e0b93bb)

## What change is required?

Replace '15' with PostgreSQL

**Comment by keichwa** [comment]
thanks for the report! merged and backported.
