### ISSUE TITLE
Typo in Ubuntu Client Registration Root Access section

### ISSUE THREAD

**Issue by rkoktan** [uyuni-project/uyuni-docs#3084]
## Documentation Update Required

Typo Ubuntu Client Registration Root Access section...

https://documentation.suse.com/suma/5.0/en/suse-manager/client-configuration/clients-ubuntu.html#_root_access
https://uyuni-micro/docs/en/uyuni/client-configuration/clients-ubuntu.html#_root_access

## What does the documentation say now?

NOTE

This issue happens with self-installed versions of Ubuntu. If the default user has been granted administrative privileges during installation time, a password is **requiered** to perform privilege escalation using sudo. With cloud instances this does not happen because cloud-init automatically creates a file under /etc/sudoers.d and grants privilege escalation through sudo without the need for a password.

## What change is required?

Change "requiered" to "required"

## Version

SUMA5 and Uyuni 2024.05 docs are so affected.

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
thanks for the report!  fixed and backported.
