### ISSUE TITLE
4.3.x Installation & Upgrade Guide > install-vm.adoc - Asciidoc tagging error

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#3085]
Revise the tagging around the 4th list item in section "Creating the VMware Virtual Machine" in https://github.com/uyuni-project/uyuni-docs/blob/manager-4.3-MU-4.3.13/modules/installation-and-upgrade/pages/install-vm.adoc#productname-virtual-machine-settings---vmware

"In menu:[Customize settings] browse to the uploaded .vmdk using IDE controller 0 storage device in the Controller Location."

'menu:[Customize settings]' is displaying in the rendered text.
![image](https://github.com/uyuni-project/uyuni-docs/assets/68334239/2d6bfb54-f133-4b5c-bf67-566e93d99c05)

The menu UI macro requires at least 2 entries.
Perhaps this should be changed to '[guimenu]``Customize settings``'.

**Comment by keichwa** [comment]
Thanks Patrick!  Fixed and backported.
