### ISSUE TITLE
Hardware requirements storage devices and permissions

### ISSUE THREAD

**Issue by kbmetz** [uyuni-project/uyuni-docs#3141]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

The wording should be changed to be more specific. Ideally referencing the volumes listed above the text. Based on the text as it is written, the customer believes this means ALL filesystems on the SUSE Manager server should be XFS.

## What does the documentation say now?

We recommend you use XFS as the filesystem type for all volumes.

## What change is required?

It should be changed to "We recommend you use XFS as the filesystem type for all volumes listed above for this section 3"

## Subject Matter Expert (SME)

The customer

## Version

4.3
https://documentation.suse.com/suma/4.3/en/suse-manager/installation-and-upgrade/hardware-requirements.html

Does the content need to be backported to previous documentation versions (if known)?
Unknown

**Comment by keichwa** [comment]
I created this PR, ready for review: https://github.com/uyuni-project/uyuni-docs/pull/3173

**Comment by keichwa** [comment]
Merged and backported (5.0 and 4.3)
