### ISSUE TITLE
Add Documentation for AppStream Configuration in Activation Keys

### ISSUE THREAD

**Issue by wweellddeerr** [uyuni-project/uyuni-docs#3186]
The current documentation for activation keys should include a mention of the capability to configure AppStreams to be automatically activated on systems using an activation key. This feature of configuring AppStreams will be available whenever a modular channel is associated with the activation key.

This feature will be introduced in the context of https://github.com/uyuni-project/uyuni/pull/8909

See https://github.com/SUSE/spacewalk/issues/24957

**Comment by keichwa** [comment]
It's merged and backported.
