### ISSUE TITLE
Uyuni - Installation and Upgrade Guide refers to Leap not Leap Micro

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-docs#3206]
Tracker issue: https://github.com/SUSE/spacewalk/issues/25491

## Documentation Update Required

With move to container-only version of Uyuni from version 2024.07, the Installation and Upgrade Guide needs updating to note Leap Micro instead of Leap.

## What does the documentation say now?

General Requirements section lists openSUSE Leap for both Server and Proxy Requirements.

![Screenshot from 2024-07-23 11-19-06](https://github.com/user-attachments/assets/19377c89-4477-412f-a637-cf7a9a61a9de)
![Screenshot from 2024-07-23 11-19-17](https://github.com/user-attachments/assets/aea2babb-674b-410f-9a44-59d2c2d44dc7)

Server section of Deployment and Installation shows openSUSE Leap in index box - note page correctly has Leap Micro.

![Screenshot from 2024-07-23 11-19-34](https://github.com/user-attachments/assets/5df318e7-b06a-4361-8c35-fc02abae581f)

## What change is required?

openSUSE Leap needs to change to openSUSE Leap Micro.

## Version

Which version of the software is this feature/update expected to land in (if known)?

2024.07

Which version of the documentation must this feature/update land in (if known)?

2024.07

Does the content need to be backported to previous documentation versions (if known)?

2024.05, possibly earlier versions.

**Comment by keichwa** [comment]
thanks!  Fixed and merged.
