### ISSUE TITLE
Information about mgr-storage-server

### ISSUE THREAD

**Issue by wtmpx** [uyuni-project/uyuni-docs#3208]
From: https://documentation.suse.com/suma/5.0/en/suse-manager/installation-and-upgrade/container-deployment/suma/server-deployment-suma.html#_configure_custom_persistent_storage 

> This step is optional. However, if custom persistent storage is required for your infrastructure, use the mgr-storage-server tool.
> For more information, see mgr-storage-server --help. This tool simplifies creating the container storage and database volumes.
> Use the command in the following manner:
```
mgr-storage-server <storage-disk-device> [<database-disk-device>]
```
To avoid confusion, please add hints where this command can be found. In SLE 5.5 with SUMA 5.0 we cannot find this command. If this part of SUMA for Public Cloud or part of pre-configured images, please write this in docu.

**Comment by mcalmer** [comment]
Yes, this comes too late to include the package into 5.0.0.
It was decided to put the files on the images we create (.vmdk, .qcow2 and cloud images) and provide the package with the first maintenance update (5.0.1) also for all the other installations.

**Comment by keichwa** [comment]
No documentation changes needed.  Issue will be gone with 5.0.1 MU.
