### ISSUE TITLE
Uyuni - Duplicate "Upgrade and Migration" sections

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-docs#3220]
## Documentation Update Required

I realise the documentation is still in flux but there are now two "Upgrade and Migration" sections in the Installation and Upgrade Guide, each with different content.

## What does the documentation say now?

There are two "Upgrade and Migration" sections.

![Screenshot from 2024-07-25 12-07-29](https://github.com/user-attachments/assets/f6f75c3d-2374-4b6c-8dce-967f43267b66)

## What change is required?

Only one "Upgrade and Migration" section with the correct content.

## Version

Which version of the software is this feature/update expected to land in (if known)?

2024.07

Which version of the documentation must this feature/update land in (if known)?

2024.07

Does the content need to be backported to previous documentation versions (if known)?

2024.05 (and earlier?)

**Comment by keichwa** [comment]
Thanks for the report!  It is fixed with .08 and further changes will be published with the next release.
