### ISSUE TITLE
Uyuni - Quick Start guide show variable on index page

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-docs#3221]
## Documentation Update Required

Quick Start guide shows variable {productname Server} on index page rather than, presumably, the value of the variable

## What does the documentation say now?

Quick Start {productname Server}

![Screenshot from 2024-07-25 12-17-43](https://github.com/user-attachments/assets/a36c00eb-7eba-4bbe-9864-2d22b8971ed9)

## What change is required?

{productname Server} should probably display as Uyuni Server

## Version

Which version of the software is this feature/update expected to land in (if known)?

2024.07

Which version of the documentation must this feature/update land in (if known)?

2024.07

Does the content need to be backported to previous documentation versions (if known)?

2024.05 (and earlier?)

**Comment by keichwa** [comment]
thanks for the report!  fixed in master branch.
