### ISSUE TITLE
Command to generate proxy configuration with self-signed certificate contains an error

### ISSUE THREAD

**Issue by roncterry** [uyuni-project/uyuni-docs#3225]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

SUSE Manager 5.0 -> Installation and Upgrade Guide -> Installation and Deployment -> Proxy -> Deploy Proxy as a Virtual Machine -> 8.2 -> step 2: 
The closing singe quote in the mgrctl exec command is in the wrong place. The closing single quote should come at the very end after -o /tmp/config.tar.gz not be for it.

This same error is also in two other places (copy and paste strikes again?): 
-SUSE Manager 5.0 -> Installation and Upgrade Guide -> Installation and Deployment -> Proxy -> Deploy SUSE Manager Proxy on SLE Micro -> 6.2 -> step 2: 
-SUSE Manager 5.0 -> Installation and Upgrade Guide -> Installation and Deployment -> Proxy -> Deploy on K3s -> 3.2 -> step 2: 

## What does the documentation say now?

mgrctl exec -ti 'spacecmd proxy_container_config_generate_cert -- dev-pxy.example.com dev-srv.example.com 2048 email@example.com' -o /tmp/config.tar.gz

## What change is required?

mgrctl exec -ti 'spacecmd proxy_container_config_generate_cert -- dev-pxy.example.com dev-srv.example.com 2048 email@example.com -o /tmp/config.tar.gz'

## Subject Matter Expert (SME)

Not known

## Version

Which version of the software is this feature/update expected to land in (if known)?  - 5.0
Which version of the documentation must this feature/update land in (if known)?  - 5.0
Does the content need to be backported to previous documentation versions (if known)?  - Not known

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
Thank you for the report.  Fixed and Backported.
