### ISSUE TITLE
Instructions to install packages is missing in Deploy SUSE Manager on SLE Micor

### ISSUE THREAD

**Issue by roncterry** [uyuni-project/uyuni-docs#3226]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

The critical step of installing the SUSE Manager packages is missing in the following document: 
SUSE Manager 5.0 -> Installation and Upgrade Guide -> Installation and Deployment -> Server -> Deploy SUSE Manager on SLE Micro

The missing step should go between 3.2 and 3.3

Without installing the packages the mgradm command is not available and Step 4 cannot be performed. Also step 3.3 wouldn't work either (once the mgr-storage-server command is actually included in the RPMs that is)

The Air-gapped section does contain the instructions for installing the required packages but it is strangely missing from the Deploy on SLE Micro section.

## What does the documentation say now?

The current docs show the following workflow:
3.1: Registration from the Command Line -> 3.2: Update the system -> 3.3 Configure Custom Persistent Storage

## What change is required?

The workflow should be:
3.1: Registration from the Command Line -> 3.2: Update the system -> 3.3 Install packages -> 3.4: Configure Custom Persistent Storage

## Subject Matter Expert (SME)

Unknown

## Version

Which version of the software is this feature/update expected to land in (if known)?  - 5.0
Which version of the documentation must this feature/update land in (if known)?  - 5.0
Does the content need to be backported to previous documentation versions (if known)?  - unknown

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by keichwa** [comment]
Maybe, it is fix in the meantime with https://github.com/uyuni-project/uyuni-docs/pull/3052 (maybe, partially).
Insternally, there is also already this tracker: https://github.com/SUSE/spacewalk/issues/24494

**Comment by keichwa** [comment]
No further doc changes needed.  Issue finally gone with 5.0.1 MU.
