### ISSUE TITLE
Uyuni - Installation and Upgrade Guide missing Container update/upgrade instructions

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-docs#3227]
## Documentation Update Required

With the change to Container-only Uyuni the Installation and Upgrade Guide is missing update and/or upgrade instructions.

## What does the documentation say now?

There are currently no instructions on updating/upgrading the Container deployment of Uyuni, either the underlying Leap Micro OS or the Uyuni container.

There are still pages (which should currently remain) on Minor and Major upgrades of the Legacy deployment of Uyuni.

## What change is required?

Need a page with instructions on updating/upgrading the Container deployment of Uyuni.

## Version

Which version of the software is this feature/update expected to land in (if known)?

Pre-2024.07

Which version of the documentation must this feature/update land in (if known)?

2024.07

Does the content need to be backported to previous documentation versions (if known)?

Yes - 2024.05 and earlier

=============
Edit:

- [x] ~https://github.com/uyuni-project/uyuni-docs/issues/3045 is somehow related (we must check the status)~
- [x] ~https://github.com/SUSE/spacewalk/issues/25298 (tracker issue)~
- [ ] https://github.com/SUSE/spacewalk/issues/25680

**Comment by simonflood** [comment]
What is required is a page like https://documentation.suse.com/suma/5.0/en/suse-manager/installation-and-upgrade/container-management/updating-server-containers.html for recently released SUMA 5.0.

Fortunately this page exists as the steps are the same for Uyuni (container), namely:

1. `transaction-update`
2. `reboot`
3. `mgradm upgrade podman`

Perhaps an extra section should be added to cover managing old Uyuni images?

**Comment by keichwa** [comment]
Thanks for the report!  Internally, we'll track it as https://github.com/SUSE/spacewalk/issues/24769.

**Comment by ppanon2022** [comment]
The Installation and Upgrade PDF for 2024.10 and linked to in the release notes still doesn't cover these steps. If the containerized version is the only supported version going forwards, it's imperative that it includes these upgrade steps. Admins shouldn't need to go searching for documentation bug reports to figure out how to do a mandatory upgrade,

**Comment by keichwa** [comment]
The `updating-server-containers.html` section is now enabled for Uyuni, too (post 2024.10).

**Comment by ppanon2022** [comment]
Thank you!
