### ISSUE TITLE
[5.0.1 L10n Installation and Upgrade Guide] Query on format in source English file

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#3290]
File: modules/installation-and-upgrade/pages/container-deployment/suma/server-migration-suma.adoc

Section: 
== Prepare the SSH Connection

Should this text be in a code box?
**PDF**
![image](https://github.com/user-attachments/assets/760d478e-ff0e-4f46-9683-73a231f6e265)

**ADOC**
![image](https://github.com/user-attachments/assets/26f018d1-ff06-4927-b465-ba494d516a29)

**Comment by keichwa** [comment]
thanks for the report (and all the others), Patrick!  fixed and merged (will be active with 5.0.2 and later).
