### ISSUE TITLE
Migration - Additional feedback and errors with fixes

### ISSUE THREAD

**Issue by digdilem** [uyuni-project/uyuni-docs#3309]
I am part way through an attempt to migrate Uyuni to container and following[ the official documentation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/container-deployment/uyuni/migrate-uyuni-to-a-container.html) 

I've found this documentation quite sparse and incomplete. To try and help, I have got as far as completing a --prepare and found several points where extra info would have been useful. 

Note: I am using Rocky9 running podman as the NEW vm (A dev confirmed the host OS doesn't matter provided it can run podman), although I imagine many of these issues are common to multiple distros.

1. 
Finding and installing the Uyuni container and migration tools, mgradm etc. 

Install golang and git:  `yum install go git`
Clone and build from the official repo: 
```
cd /usr/src/
git clone https://github.com/uyuni-project/uyuni-tools.git
cd uyuni-tools
mkdir bin
go build -o ./bin ./...
```
(Without the bin dir, the build fails. The binaries should now exist in there and can be copied to a path directory. Read uyuni-tools readme for details on adding bash completion)

2. 
Error encountered when running prepare/migrate command: `mgradm migrate podman --prepare --logLevel debug oldserver.fqdn`

```
2:30PM FTL mgradm/cmd/migrate/shared/shared.go:20 > SSH_AUTH_SOCK is not defined, start an SSH agent and try again
```

This seems to happen because the NEW server needs ssh-agent configuring as an additional step. 

To fix:

```
(Assuming you created ssh keys and setup passwordless login as per the official guide's ssh section. )
a) Add the key to ssh-agent: ssh-add /root/.ssh/id_rsa

b) Run: eval ssh-agent
	Output will be something like:
	SSH_AUTH_SOCK=/tmp/ssh-XXXXXXVT6tqW/agent.7384; export SSH_AUTH_SOCK;
	SSH_AGENT_PID=7385; export SSH_AGENT_PID;
        echo Agent pid 7395;


Copy and paste the two lines with 'export` into your session. Without this, mgradm cannot create ssh connections to the old server.
```

3. 
Error: rsync: [receiver] write failed on "/var/spacewalk/systems/1/1000010504/actions/818715/results.xml": No space left on device (28)
Ensure you have enough free space. The documentation doesn't currently say where you need the space if you have separate partitions. This location is: `/var/lib/containers/storage/volumes`
My old Uyuni server had 103Gb used including OS but few repos. The new server used 75Gb.

4. 
`Error: Error: netavark: code: 1, msg: iptables: Chain already exists.`
This occurs whenever mgradm fails for any reason. If this error seems unclear where iptables is running, it's because it's nothing to do with iptables, at least on Rocky9. 
The fix is to restart _nftables_ on the new host: `systemctl restart nftables`
(I'm assuming the script creates a temporary rule, but has no test to see whether it exists already)

I hope these help others with this migration, and the doc team to improve the migration team.

**Comment by simonflood** [comment]
Note that there's an Enterprise Linux 9 repo for the Uyuni container utils available at https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/EL_9/ (inc. repo file) so no need to clone from git and build.

**Comment by digdilem** [comment]
Update: I gave up with migrating to EL. the migration script is too finely tuned to run on Leap 5.5. Things like the above, plus it calls functions that are named differently - erroring out because update-certificates-ca is named differently on the two distros for example. 

I tried it with Leap Micro and it did migrate without any of the above errors. The only issue was that the --prepare function prevented a later full migration; that part seems broken. 

It's probably easier to convert to podman using the tested Leap Micro route and then migrate the container stack to another distro once it's there. 

Fine to close this if team think it's not of wider use.

**Comment by keichwa** [comment]
Thanks @digdilem for checking the documentation and providing feedback and improvement proposals!

Your report has at least two aspects:

- Clarify on the documentation level what's supported and what's not
- Discussion about future support coverage and implementation

Maybe, it would be the best to split this report accordingly.
