### ISSUE TITLE
OES missing from supported clients for Uyuni and SUMA

### ISSUE THREAD

**Issue by simonflood** [uyuni-project/uyuni-docs#3312]
## Documentation Update Required

Micro Focus/OpenText Open Enterprise Server (OES) missing from list of supported clients for Uyuni and SUMA 4.3/5.0

## What does the documentation say now?

Currently the list of supported clients for Uyuni and SUMA 4.3/5.0 does not include any version of Micro Focus/OpenText Open Enterprise Server (OES).

## What change is required?

Micro Focus/OpenText Open Enterprise Server (OES) versions 2023 and 23.4 (at least*) should be included in the list of supported clients.

*these are the OES versions I checked - each has a section in their documentation referencing using SUSE Manager to patch an OES server

 * 23.4: https://www.microfocus.com/documentation/open-enterprise-server/23.4/inst_oes_lx/b14xjmht.html
 * 2023: https://www.microfocus.com/documentation/open-enterprise-server/2023/inst_oes_lx/b14xjmht.html

I also found an GitHub discussion from November 2023 where support for OES 23.4 was awaiting blessing by Micro Focus/OpenText - https://github.com/uyuni-project/uyuni/discussions/7886 . Checking Uyuni 2024.08 the referenced file now has "OES2" instead of "OES2-BETA" for the product_class.

## Version

Which version of the software is this feature/update expected to land in (if known)?

 * Uyuni > 2023.10 <= 2024.08
 * SUSE Manager 4.3 & 5.0

Which version of the documentation must this feature/update land in (if known)?

 * Uyuni > 2023.10 <= 2024.08
 * SUSE Manager 4.3 & 5.0

Does the content need to be backported to previous documentation versions (if known)?

Possibly (depends on when support for OES 23.4/2023 was added to Uyuni)

**Comment by keichwa** [comment]
Backport are still open, but we dealt with it.  To be published with next uyuni and SUMA MU 5.0.3.
