### ISSUE TITLE
Migration Page should have a requirements section 

### ISSUE THREAD

**Issue by gabrielstein** [uyuni-project/uyuni-docs#3313]
## Documentation Update Required

Add the requirements to start a migration from 4.3 to 5.x

## What does the documentation say now?

- There are no requirements

## What change is required?

Add the requirements to the page before describing the migration process.

Requirements:

- A SLE-Micro 5.5 with mgradm installed (do not install SUSE Manager on this Server, the migration process will take care)

## Subject Matter Expert (SME)

-

## Version

Which version of the software is this feature/update expected to land in (if known)? 5.x
Which version of the documentation must this feature/update land in (if known)? 5.x
Does the content need to be backported to previous documentation versions (if known)? No

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by 0rnela** [comment]
Fixed.
