### ISSUE TITLE
The Package Hub is required to install helm - Proxy required tools

### ISSUE THREAD

**Issue by gpoppino** [uyuni-project/uyuni-docs#3323]
## Documentation Update Required

The documentation mentions that `helm` is a tool required to be able to install the proxy server on a K3s environment, and it says this tool is part of the Containers Module when there is no Containers Module for SLE Micro 5.5.

## What does the documentation say now?

It mentions: "The Containers Module is required to install helm."

## What change is required?

The change should be something like: "The SUSE Package Hub Module is required to install helm."

The location of this note should be in https://documentation.suse.com/suma/5.0/en/suse-manager/installation-and-upgrade/container-deployment/suma/proxy-k3s-deployment-suma.html#installation-proxy-containers-k3s-helm

For internal tracking: https://github.com/SUSE/spacewalk/issues/25462

**Comment by deneb-alpha** [comment]
@uyuni-project/documentation before implementing this change, let's follow-up on https://suse.slack.com/archives/C02C40VR10A/p1727197029713069

**Comment by keichwa** [comment]
merged and backported to 5.0 (for 5.0.2 or later).
