### ISSUE TITLE
Doc PRs: build and publish to some temporary place for easier review

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni-docs#35]
Reviewing pull requests in uyuni-docs is sometimes difficult because of the placeholders, replacements, lack of context, etc in the GitHub code review tool.

Would it be possible to use GitHub Actions to automatically build the docs in the PR branch and publish them to some place (e. g. uyuni-project.org/uyuni-docs-devel/prXXXX) so that the review is easier? After the PR is merged or closed, those can be removed again using GitHub Actions.

**Comment by Loquacity** [comment]
@jcayouette have you seen this?

@paususe to the best of my knowledge, that is planned (or could already be happening).

**Comment by Loquacity** [comment]
Please track this in spacewalk.
