### ISSUE TITLE
Links in the Documentation seem to be incorrect.

### ISSUE THREAD

**Issue by thegreatluke** [uyuni-project/uyuni-docs#428]
If you start at "https://www.uyuni-project.org/" and click "Documentation" in the top menu. It leads to: "https://www.uyuni-project.org/uyuni-docs/uyuni/index.html", from there using the tree menu on the left and navigating to "
Install Uyuni Server with openSUSE" does not appear to have the updated info for the installation guide. Recommends leap 15.1 etc...

The "real" docs for the stable branch appear to be here: https://www.uyuni-project.org/pages/stable-version.html --> I can't find a link to this anywhere on uyuni-project.org. I actually followed a link from the uyuni-project twitter account to https://lists.opensuse.org/uyuni-announce/2020-07/msg00000.html --> which lead me full circle to https://www.uyuni-project.org/pages/stable-version.html 

Anyway... I'm trying to test this thing out since we might be migrating away from RHEL. Happy to help with docs or to keep the website links current, haven't gone through all the contributing docs yet. But I thought you all would like to know.

**Comment by Loquacity** [comment]
Thanks for this report, and for spending the time following this around. We will look into this and see what's going on.

**Comment by jcayouette** [comment]
Oof! Nice catch thanks Luke!

**Comment by Loquacity** [comment]
Updated the docs so that they don't reference old versions of Leap, and created an internal issue to track the broader issue of the Quickstart Guide. Luke: thanks again for noticing this!
