### ISSUE TITLE
Adjust custom-channels.adoc for uyuni

### ISSUE THREAD

**Issue by keichwa** [uyuni-project/uyuni-docs#43]
ATM, administration/pages/custom-channels.adoc is confusing for uyuni users.  uyuni does not necessarily provide "all required channels".  Thus this intro and maybe more must be adjusted:

> While {productname} provides all required channels, you might find it useful to create custom channels specific to your environment.

**Comment by Loquacity** [comment]
Tracking in https://github.com/SUSE/spacewalk/issues/10581
