### ISSUE TITLE
Add "Debian Client Registration" to the Client Registration Navigation Page

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#461]
Could you please add "Debian Client Registration" to the Client Registration Navigation Page
https://github.com/uyuni-project/uyuni-docs/blob/master/modules/client-configuration/nav-client-configuration-guide.adoc

https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-ubuntu.html
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-debian.html

OLD: 
// Ubuntu Client Registration
** xref:registration-overview-ubuntu[Ubuntu Client Registration]
*** xref:clients-ubuntu.adoc[Ubuntu 20.04 Clients]
*** xref:clients-ubuntu-old.adoc[Ubuntu 16.04 and 18.04 Clients]
ifeval::[{uyuni-content} == true]
*** xref:clients-debian.adoc[Debian Clients]
endif::[]

NEW:
// Ubuntu Client Registration
** xref:registration-overview-ubuntu[Ubuntu Client Registration]
*** xref:clients-ubuntu.adoc[Ubuntu 20.04 Clients]
*** xref:clients-ubuntu-old.adoc[Ubuntu 16.04 and 18.04 Clients]
ifeval::[{uyuni-content} == true]
// Debian Client Registration
** xref:registration-overview-debian.adoc[Debian  Client Registration]
*** xref:clients-debian.adoc[Debian Clients]
endif::[]

**Comment by Loquacity** [comment]
Great spot, thanks!
