### ISSUE TITLE
Add Debian-9/10 Systems to the table of "Supported Client Systems" 

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#462]
Could you please add Debian-9/10 Systems to the Table 1. Supported Client Systems 
https://github.com/uyuni-project/uyuni-docs/blob/master/modules/client-configuration/pages/supported-features.adoc#supported-client-systems

see also: 
https://www.uyuni-project.org/pages/stable-version.html
Each supported Operating System has a repository, for all supported architectures:
SNIP
•	Debian 9 (x86_64, aarch64, armv7l, i586)
•	Debian 10 (x86_64, aarch64, armv7l, i586)

https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/supported-features-debian.html

Release Notes:
https://www.uyuni-project.org/doc/2020.07/release-notes-uyuni-server.html

Version 2020.03
Debian client tools
We now offer Debian client tools that allow for easy onboarding of Debian as salt minions, as well as running spacecmd from them.
Check the Client Configuration Guide for information about how to configure Uyuni Server to work with Debian clients.
For now the following architectures are supported: x86_64, aarch64, armv7l, i586
We plan to continue improving Debian support in the future, including support for ppc64le and s390x Debian 10 clients.

https://www.uyuni-project.org/doc/2020.07/release-notes-uyuni-server.html#_enhanced_support_for_debian_and_ubuntu

**Comment by Loquacity** [comment]
The current Uyuni docs have Debian 9/10 listed: https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/supported-features.html

![image](https://user-images.githubusercontent.com/3914967/90995618-ca334400-e5ff-11ea-9d2a-935539221a83.png)

From my reading, this resolves the issue. Can you please confirm?

**Comment by Shirocco88** [comment]
at the Moment "cpuach: x86_64" for Debian 9/10 is IMHO OK;
I will test Onboarding of Debian-Clients with cpuarch=aarch64, osarch=arm64


https://www.uyuni-project.org/pages/stable-version.html
Each supported Operating System has a repository, for all supported architectures:
SNIP
• Debian 9 (x86_64, aarch64, armv7l, i586)
• Debian 10 (x86_64, aarch64, armv7l, i586)

**Comment by Shirocco88** [comment]
at the Moment "cpuach: x86_64" for Debian 9/10 is IMHO OK;
I will test Onboarding of Debian-Clients with cpuarch=aarch64, osarch=arm64


https://www.uyuni-project.org/pages/stable-version.html
Each supported Operating System has a repository, for all supported architectures:
SNIP
• Debian 9 (x86_64, aarch64, armv7l, i586)
• Debian 10 (x86_64, aarch64, armv7l, i586)

**Comment by Shirocco88** [comment]
at the Moment "cpuach: x86_64" for Debian 9/10 is IMHO OK;
I will test Onboarding of Debian-Clients with cpuarch=aarch64, osarch=arm64


https://www.uyuni-project.org/pages/stable-version.html
Each supported Operating System has a repository, for all supported architectures:
SNIP
• Debian 9 (x86_64, aarch64, armv7l, i586)
• Debian 10 (x86_64, aarch64, armv7l, i586)

**Comment by Loquacity** [comment]
OK, no problem, I can put these in for you :+1:

**Comment by Shirocco88** [comment]
@Loquacity 
Thanks!!! :thumbsup:

if there is a problem with Bootstrapping of Debian RaspberryPI4s (cpuarch=aarch64, osarch=arm64), then I'll open an issue @uyuni
