### ISSUE TITLE
Set "{uyuni-content} == true" as default in adoc files

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#467]
at the Moment the Online Docs at uyuni-docs didn't Show all Content for Uyuni Server; e.g.
the Debian Pages for Debian Systems aren't shown, 

Could you please set  "{uyuni-content} == true" as default in adoc files or Change the if clause to "{suma-content} == false"

**Comment by Loquacity** [comment]
We can't change the logic at this stage. However, we understand that the current method is less than ideal, and we intend to address it with a much more complete solution in the near future. As to the specific issue of the Debian client page not showing up, that's a bug, and I'll open a PR against  https://github.com/uyuni-project/uyuni-docs/issues/461 to fix that today for you.
