### ISSUE TITLE
Feature "Apply Patches" @Ubuntu 20.04 / 18.04 / 16.04 is OK with Salt-Minions

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#475]
Hallo Uyuni-Team,
Is there a reason why this feature is flagged "unknown" in Table 1. Supported Features on Ubuntu Operating Systems ?
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/supported-features-ubuntu.html

It would be fine, if this feature would be marked as OK for salt minions

Best regards
Shirocco88

**Comment by jcayouette** [comment]
As far as the developers know there is no way to import patches into Uyuni for these systems. Have you tested this? If so how did you accomplish it?

**Comment by Shirocco88** [comment]
@jcayouette: 
"Applying Patches to Clients" is descript in the following docu:
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/patch-management.html#_apply_patches_to_clients

>> As far as the developers know there is no way to import patches into Uyuni for these systems. 

"import patches" ???
there is no need to "import patches" to clients;

do you meen "Import Errata to Channels" ?
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-centos.html#_manage_errata
see also "CVE auditing" and "SCAP auditing" in the table 1 Supported Features on Ubuntu Operating Systems would help

what does the developer say, what is not working, maybe I have overseen something.

Best regards
Shirocco88

**Comment by Shirocco88** [comment]
further analysis done;
currently "Apply Patches" is not a supported feature of Debian/Ubuntu;
therefore this issue can be closed.
