### ISSUE TITLE
Ubuntu 20.04 is missing in Table of Supported Features of Ubuntu Operating Systems

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#476]
Hallo Uyuni-Team,
Ubuntu 20.04 is missing in Table of Supported Features of Ubuntu Operating Systems;
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/supported-features-ubuntu.html

Could you please add a colum with Ubuntu 20.04 Features.

Thanks in Advance.

Best regards
Shirocco

**Comment by jcayouette** [comment]
Already fixed in master. 
- https://github.com/uyuni-project/uyuni-docs/blob/master/modules/client-configuration/pages/supported-features.adoc
- https://raw.githubusercontent.com/uyuni-project/uyuni-docs/master/modules/client-configuration/pages/supported-features-ubuntu.adoc

**Comment by Shirocco88** [comment]
@jcayouette
>> Already fixed in master.
I couldn't find the Changes for Uyuni-Server:

`
ifeval::[{uyuni-content} == true]

[cols="1,1,1", options="header"]
.Supported Features on {ubuntu} Operating Systems
|===

| Feature
| {ubuntu}{nbsp}16.04
| {ubuntu}{nbsp}18.04
`
>> You will see the update when we release 2020.08
I was checking Master not a future stable release.

Best regards.
Shirocco88

**Comment by Shirocco88** [comment]
see also Uyuni-Project page:
https://www.uyuni-project.org/
14/07/2020
Uyuni 2020.07 is now available! Base OS for server and proxy is now Leap 15.2 and it includes PostgreSQL 12 and Salt 3000. Ubuntu 20.04 can now be managed as a client, and much more changes! Check https://www.uyuni-project.org/pages/stable-version.html#releasenotes for more details!

And Release Notes for Uyuni-Server 2020.07>
https://www.uyuni-project.org/doc/2020.07/release-notes-uyuni-server.html#_ubuntu_20_04_lts
Ubuntu 20.04 LTS
Starting with Uyuni  2020.07, Ubuntu 2020.04 LTS is supported as a client.

**Comment by Loquacity** [comment]
Oh, I see. We're missing the column in the Ubuntu page. I can add this.

**Comment by jcayouette** [comment]
Ah nice catch @Shirocco88
