### ISSUE TITLE
Ubuntu 20.04 is missing in Table of Supported Operating Systems

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#478]
Hallo Uyuni-Team,
Ubuntu 20.04 is missing in Table of Supported Operating Systems;
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/supported-features.html

Could you please add Ubuntu 20.04 in Table of Supported Operating Systems.

Thanks in Advance.

Best regards
Shirocco88

**Comment by Loquacity** [comment]
This has been fixed in master, and will be refreshed online shortly.
