### ISSUE TITLE
Please change Recommended OS for Uyuni Server/Proxy from "openSUSE Leap 15.1" to 15.2

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#479]
Hallo Uyuni-Team,
Please change Recommended OS for Uyuni Server/Proxy from "openSUSE Leap 15.1" to 15.2
see https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-install-requirements.html

Best regards.
Shirocco88

**Comment by Shirocco88** [comment]
Update:
another Page found:
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html

**Comment by Shirocco88** [comment]
Update:
more pages to be updated found:
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-proxy-uyuni.html

**Comment by Shirocco88** [comment]
Update:
more pages to be updated found:
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-uyuni.html
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/install-proxy-uyuni.html
https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-proxy-registration.html

**Comment by jcayouette** [comment]
Great thanks for catching these!

**Comment by Loquacity** [comment]
These were fixed in a PR that merged only a few days ago, so they'll be refreshed online shortly.
