### ISSUE TITLE
Typo Error "Packages Provided by {suse} Package Hub" ?

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#480]
Hallo Uyuni-Team,
I don't know what "Packages Provided by {suse} Package Hub"
see:
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/channels.html#_packages_provided_by_suse_package_hub

Maybe a Typo ?

Best Regards.
Shirocco88

**Comment by Loquacity** [comment]
Ah, this is interesting. The entity in question is {phub} which is defined as '{suse} Package Hub', so it seems the {suse} entity is not resolving properly. I can fix this.
