### ISSUE TITLE
Typo Error "<<client-cfg-autoinstallation-prep>>"

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#481]
Hallo Uyuni-Team,
the following Link is not working:
===========================================================
A Uyuni Proxy is a SLE client with a special role. You can install it using AutoYaST.
Create an autoinstallation tree as outlined in [client-cfg-autoinstallation-prep].
===========================================================
https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/client-automating-preparation.html#client-cfg-autoinstallation-prep

Typo Error ?
Create an autoinstallation tree as outlined in <<client-cfg-autoinstallation-prep>>.
https://raw.githubusercontent.com/uyuni-project/uyuni-docs/master/modules/client-configuration/pages/client-automating-preparation.adoc

Best regards.
Shirocco88

**Comment by Loquacity** [comment]
Ah, because the link is linking to itself :woman_facepalming:
