### ISSUE TITLE
Docu about Supported Migration paths is incomplete, e.g. SLES15 is missing

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#483]
Hallo Uyuni-Team,
the docu about Supported Migration paths is incomplete, e.g. SLES15 is missing

https://www.uyuni-project.org/uyuni-docs/uyuni/reference/systems/system-details/sd-sp-migration.html
e.g.  
SLE 15 > SLE 15 SP1 > SLE 15 SP2 

Could you please add Supported Migration paths for SLES15

Best regards
Shirocco88

**Comment by Loquacity** [comment]
This seems really old. We'll need to review it. @keichwa this might be a good one for you?

**Comment by keichwa** [comment]
Thanks for spotting!

**Comment by keichwa** [comment]
I asked for feedback. With restructuring the Reference Guide, we now must provide this information differently.

We also must cover Uyuni clients.

**Comment by keichwa** [comment]
Thank you for the report.  It is now fixed in master (for the next uyuni release and suse manager 4.2 and later, and for the next 4.1 maintenance release).
