### ISSUE TITLE
For all versions and formats of the Uyuni documentation, see https://documentation.suse.com/suma/.

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#484]
Hallo Uyuni-Team,
why should I see  https://documentation.suse.com/suma/ if I would have a look at Uyuni Docu ?

======================================================================
https://www.uyuni-project.org/uyuni-docs/uyuni/reference/help/documentation-version.html

For all versions and formats of the Uyuni documentation, see https://documentation.suse.com/suma/.
======================================================================

Best regards
Shirocco88

**Comment by Shirocco88** [comment]
there are more such links:

https://www.uyuni-project.org/uyuni-docs/uyuni/reference/help/api-overview.html
For the full API documentation, see https://documentation.suse.com/suma/.

**Comment by Shirocco88** [comment]
https://www.uyuni-project.org/uyuni-docs/uyuni/quickstart-public-cloud/qs-publiccloud-intro.html
For more information on using Uyuni, see the official Uyuni documentation at https://documentation.suse.com/suma.

**Comment by Loquacity** [comment]
At the moment, Uyuni documentation is built from SUMA sources. This is more or less a stop-gap solution while we gather resources for writing Uyuni-specific docs, and we understand that it's less than ideal. This is on our plan to correct in the coming months, so you will start to see many more changes for Uyuni docs soon. In the meantime, we're really happy to have some eyes on the Uyuni docs as they are, and we're going to need your feedback even more as we start releasing better docs for our community :heart:
