### ISSUE TITLE
Broken link in salt-ssh-push.adoc 

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#495]
Hallo Uyuni-Team,
there is a broken Broken link in salt-ssh-push.adoc 
https://wiki.microfocus.com/index.php/SUSE_Manager/SaltSSHServerPush

Please fix Page:
https://github.com/uyuni-project/uyuni-docs/blob/master/modules/architecture/pages/salt-ssh-push.adoc#for-more-information

Best regards
Shirocco88

**Comment by Loquacity** [comment]
Ah, great spot!
