### ISSUE TITLE
Broken link in devel-version.html

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#496]
see:
https://www.uyuni-project.org/pages/devel-version.html#documentation

it points to itself; this makes less sense;
please change the link to the correct location.

Best regards
Shirocco88

**Comment by juliogonzalez** [comment]
@Shirocco88 tthis repository is only for the documentation.

The website has its own repository at https://github.com/uyuni-project/uyuni-project.github.io, where you can also easily contribute with PRs (all the code for the content itself is HTML).

**Comment by Shirocco88** [comment]
@juliogonzalez:
Thanks for Link to https://github.com/uyuni-project/uyuni-project.github.io

I'll start to contribute my first PRs, if possible.

**Comment by Shirocco88** [comment]
Fixed:
Update devel-version.html, add Ubuntu-20.04 #26
https://github.com/uyuni-project/uyuni-project.github.io/pull/26
