### ISSUE TITLE
Typo error in salt-ssh-push.html

### ISSUE THREAD

**Issue by Shirocco88** [uyuni-project/uyuni-docs#497]
Please corecct the following page:
https://www.uyuni-project.org/uyuni-docs/uyuni/architecture/salt-ssh-push.html
For more information about activation keys, see: _**xref:ref.webui.systems.activ-keys**_.

**Comment by Loquacity** [comment]
Good one. On these smaller things, you can always create a pull request yourself. Let us know if you need any help with that :)
