### ISSUE TITLE
Improve terminology in Salt Guide?

### ISSUE THREAD

**Issue by tomschr** [uyuni-project/uyuni-docs#514]
# Situation

Just reading the terminology section in the [Salt Guide](https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/salt/salt-terminology.html). This is great that we have such a guide! :+1:  Especially, as a newbie, I'm happy that I can use and educate myself when it comes to Salt.

Reading this terminology from a perspective as a newbie, I've observed these issues:

* Missing terms
* Indentation
* Mixing term definitions and user actions

# Proposed Solution

* Missing terms
   I guess, we don't need to explain every term in our terminology section. Especially as there is a dedicated glossary section upstream (see link below). However, especially as a newbie looking at this section, I have the feeling there are some (important?) terms missing. For example "(Salt) Module", "Minion", "Formulas", "(Salt) Master", and probably more. 

* Indentation
  It seems to me, the indentation for some terminology terms are off. For example, for the term "Grains", the second paragraph "When you run a Salt command..." starts **un**indented. For me, this gives me the feeling this is something new and doesn't belong to this term. However, IMHO, this paragraph belongs to this term and as such it should be indented. Other terms are also affected. 

* Mixing term definitions and user actions
  IMHO a terminology is about terms and their definitions. It's an _informative_ document. It's not a howto. Therefor, I'd avoid sentences like "List all available grains with the...".  If you want to keep these things, I'd suggest to move them into a different section. You could still add a link (See section 123 about using...).

Hope that makes sense. :wink: 

# Additional Links

* https://docs.saltstack.com/en/latest/glossary.html
* https://susedoc.github.io/doc-slesforsap/master/html/SLES-SAP-sol-automation/#sec-sol-autom-terms

**Comment by Loquacity** [comment]
Ah, yes, this page definitely needs love. Thanks for the detailed report!
