### ISSUE TITLE
SUSE Manager channel sync problems - From supporters

### ISSUE THREAD

**Issue by jcayouette** [uyuni-project/uyuni-docs#515]
https://www.suse.com/support/kb/doc/?id=000018198 -> would it make sense to add that to our docu maybe? 

A bit like https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/large-deployments/tuning.html maybe? 

Also it would be good to add a note to that docu stating what (and "if") services need to be restarted (and "how")?

**Comment by Loquacity** [comment]
I'd put this in the troubleshooting section of the Admin Guide, personally.
