### ISSUE TITLE
 SUSE Manager 4.1 Documentation - Users

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#546]
originally reported by @jorx-dev at https://github.com/doc-suse-com/issue-tracker/issues/43:

> Hello,
> In the Administration Guide of SUSE Manager's Users section there is an statement that I think is incomplete. At the beginning just after the 1st paragraph, it reads:
> 
> NOTE: The Users menu is only available if you are logged in with a SUSE Manager administrator account.
> 
> I think I should be:
> 
> NOTE: The Users menu is only available if you are logged in with a SUSE Manager administrator account or an Organization administrator account.
>
> regards,

**Comment by Loquacity** [comment]
Thanks for the report, we'll get that fixed up.
