### ISSUE TITLE
upgrade examples: I s networking a valid section? 

### ISSUE THREAD

**Issue by mmeiste** [uyuni-project/uyuni-docs#561]
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/upgrade/proxy-x.html
refers to: https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST

Examples here for upgrading e.g.:
https://github.com/SUSE/manager-build-profiles/blob/master/AutoYaST/SUSE%20Manager%20Proxy-Upgrade-3.2-to.4.1/autoyast.xml

contain a "<networking..." section where I wonder if this is correct as within autoupgrade section of autoyast it lists only:
https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-configuration-installation-options.html#CreateProfile-upgrade
scripts/pre-scripts
add-on
language
timezone
keyboard
software
suse_register
backup
upgrade

**Comment by Loquacity** [comment]
@mbologna Can you help here?

**Comment by mbologna** [comment]
@mmeiste : I am not sure if the AutoYaST networking section is right

I did some (git) history digging, and that AutoYaST file was originally introduced by @keichwa : https://github.com/uyuni-project/uyuni-docs/commit/02d6a4f25161f4c6b39afa81249d88637b787146

@keichwa : maybe you have more context about the AutoYaST question above?

**Comment by Loquacity** [comment]
I suspect it goes further back than that. The file was originally in the doc proper, and got moved into the git repo.

**Comment by keichwa** [comment]
At least, we have /usr/share/YaST2/schema/autoyast/rng/networking.rng and it is mentioned in the include file.  Does this statement do harm if specified in the autoyast file, @mmeiste ?  If yes, we might need a bug report or ask @mcalmer for help.  Unfortunately, I'm not that familiar with autoyast.

**Comment by mmeiste** [comment]
Hi, I would not expect that an unknown config element <networking> may cause any issues beside confusing users.

**Comment by keichwa** [comment]
Thanks for investigation!  I'm going to remove it.

**Comment by keichwa** [comment]
@mbologna I created a PR.

**Comment by mbologna** [comment]
> @mbologna I created a PR.

Thanks! PR merged
