### ISSUE TITLE
openscap scans in Salt Clients

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#565]
reported by @jorx-dev in https://github.com/doc-suse-com/issue-tracker/issues/44 on Sep 24, 2020:

> Hello,
> 
> On https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/administration/openscap.html there is a note at the beginning that claims oscap scans only work for traditional clients.
> 
> NOTE: OpenSCAP auditing is available for use with traditional clients only. It is not available on Salt clients.
> 
> In my case, I've been able to launch oscap scans on a SLES 15 SP1 Salt Client from the SUSE Manager WebUI. So what's wrong ?
> 
> thanks,

**Comment by Loquacity** [comment]
This has been updated in the latest version, and will be live soon.
