### ISSUE TITLE
support clients list incomplete

### ISSUE THREAD

**Issue by jmozd** [uyuni-project/uyuni-docs#566]
The release notes at https://www.suse.com/releasenotes/x86_64/SUSE-MANAGER/4.1/#_major_changes_since_suse_manager_server_4_0 state that "The Ubuntu 20.04 LTS product is now managed as a vendor channel and repository URLs (but not packages or metadata) come from SCC directly, so there is no need to use spacewalk-common-channels or manually add the repository URLs."

The matrix of supported clients only has rows for 16.04 and 18.04. (https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/supported-features.html)

**Comment by Loquacity** [comment]
Thanks for the report. This has been fixed in the latest version, and will be updated online soon.
