### ISSUE TITLE
Migration troubleshooting log not mentioned

### ISSUE THREAD

**Issue by rkoktan** [uyuni-project/uyuni-docs#569]
There is no mention (that I can find) of the /var/log/rhn/migration.log file in the SUMA 4.1 docs to allow customers (and support engineers!) to troubleshoot failed migrations.  I only see "MANAGER_SETUP_COMPLETE" on the target system mentioned, but it only indicates success or failure, no other info.  I suspect it ought to be mentioned in the Upgrade Guide-Troubleshooting section.

**Comment by rkoktan** [comment]
Oh, and that it is found on the target system as well...

**Comment by Loquacity** [comment]
Good spot, thanks!
