### ISSUE TITLE
Hostname Note needs to be moved in the migration process steps.

### ISSUE THREAD

**Issue by rkoktan** [uyuni-project/uyuni-docs#587]
In the Server - Major Version Upgrade (X Upgrade) section, the Note...

During the migration process, the target system will fake its hostname to match the source system. Do not change the hostname during the process. Be careful when you log in to your systems during migration, as they will both show the same hostname.

... ought to be moved to between Step 1 and Step 2.  It should also be specified in BOLD that the source and target hostnames CANNOT match prior to beginning the migration process.  We in Support are seeing customers using different IPs but the same hostname for the target SUMA systems, and this is causing the migration to fail because they are not reading through the docs completely and so aren't noticing this small but vital step.

**Comment by Loquacity** [comment]
Great suggestion, thanks!
