### ISSUE TITLE
SP Migration links to Major Release Upgrade

### ISSUE THREAD

**Issue by thallma** [uyuni-project/uyuni-docs#592]
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/reference/systems/system-details/sd-sp-migration.html links to https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/upgrade/client-y-z.html

**Comment by Loquacity** [comment]
A Y upgrade is a minor upgrade, and a Z upgrade is an SP upgrade: 
![image](https://user-images.githubusercontent.com/3914967/95400911-3b7c4b80-094f-11eb-9575-6fe908c379fb.png)

That said, the Upgrade Guide is definitely looking a little out of order, and I thought we'd ditched the X/Y/Z naming already. Let's use this issue to go through it and fix.
