### ISSUE TITLE
Client Upgrade section discusses Major Release Upgrades only

### ISSUE THREAD

**Issue by thallma** [uyuni-project/uyuni-docs#593]
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/upgrade/client-intro.html just describes Major Release Upgrades. It seems there is no SP Migration anywhere described in detail. Just the highlight description that then links to Major Release Upgrade process.

**Comment by Loquacity** [comment]
Duplicate of https://github.com/uyuni-project/uyuni-docs/issues/592
