### ISSUE TITLE
no chapter anymore how to register public cloud PAYG clients.

### ISSUE THREAD

**Issue by petersatsuse** [uyuni-project/uyuni-docs#595]
in older SUMa documentation there was a small chapter on how to de-register the PAYG instance from the cloud update infrastructure. I could not find this anymore in the actual documentation.

https://documentation.suse.com/external-tree/en-us/suma/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/_suse_manager_in_the_public_cloud_suse_manager_server_and_suse_manager_proxy_in_the_public_cloud.html

https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/public-cloud.html
(even this was only visible through search and not over menu)

**Comment by Loquacity** [comment]
This is already on the docs radar, and being addressed in https://github.com/uyuni-project/uyuni-docs/pull/563
