### ISSUE TITLE
Uyuni 4.0.2 - reference guide - pdf differes from html -> 'Salt Catalog' instead of 'Formula catalog'

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni-docs#6]
I have checked the reference guide for Uyuni 4.0.2 and it seems to have a mistake:

Go to -> Help -> Reference Guide -> PDF.

In section WebUI (13/249) the guide claims that there is a:
>State Catalog
>Create, store, and manage states for your Salt clients from the State Catalog.

But it should be a 'Formula Catalog' instead.

**Comment by hunter86bg** [comment]
As the issue is only in the PDF, I guess the data is already in the git.

**Comment by Loquacity** [comment]
It's "Formula Catalog" in /develop (and I double check the nav is correct for both HTML & PDF), so we probably just need to refresh the PDF online. @jcayouette can you take a look, please?

**Comment by hunter86bg** [comment]
It seems that I didn't mention that uyuni internal's help shows a difference between the pdf and the html doc, so I guess the relevant rpm should be rebuild.

At work, we use extensively our SUMA's built-in reference guide, due to firewall  limitations.

**Comment by hunter86bg** [comment]
So the difference is both online and offline.

**Comment by jcayouette** [comment]
@hunter86bg Thanks! I will take a look. :+1:

**Comment by jcayouette** [comment]
Ahh This is a bug. Apologies we did not update the content here. 

https://www.suse.com/documentation/suse-manager-4/4.0/suse-manager/reference/navigation/categories-and-pages.html

I will make the correct adjustments. :)

**Comment by hunter86bg** [comment]
I guess in the next version , the offline doc will also be in sync.

**Comment by Loquacity** [comment]
@jcayouette can we close this now?
