### ISSUE TITLE
Incorrect URL in Uyuni theme

### ISSUE THREAD

**Issue by jcayouette** [uyuni-project/uyuni-docs#608]
Clicking the report issue bug icon upper right directs to the old repo doc-susemanager. Needs to point to uyuni-docs/issues

**Comment by Loquacity** [comment]
Looks correct in latest:

![image](https://user-images.githubusercontent.com/3914967/96668205-f9ff8d80-139d-11eb-95e7-faece0a0b2be.png)

**Comment by Loquacity** [comment]
Reopening for 4.0 on d.s.c (4.1 is fine):

![image](https://user-images.githubusercontent.com/3914967/96818145-38f81680-1464-11eb-8617-3b5dd6a3c0a1.png)

**Comment by jcayouette** [comment]
This has been corrected. Closing
