### ISSUE TITLE
Synchronize SMT instructions include rmt command

### ISSUE THREAD

**Issue by pwl0lwp** [uyuni-project/uyuni-docs#619]
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/administration/disconnected-setup.html#_synchronize_smt

Step 3 is 

```
    Export the enabled repositories to your removable storage:

rmt-cli export settings /mnt/usb
```

the rmt-cli command doesn't exist with SMT.   This looks like a copy-paste error from the portion above

**Comment by Loquacity** [comment]
Thanks for the report. Do you know the correct command?

**Comment by pwl0lwp** [comment]
I don't think there is one - looking at the the SUSE Manager 3.2 guide...

**Comment by pwl0lwp** [comment]
Check with Lasith Haturusinha in the ANZ SE team
