### ISSUE TITLE
Document the various way to create VMs for Salt minions

### ISSUE THREAD

**Issue by cbosdo** [uyuni-project/uyuni-docs#620]
With https://github.com/uyuni-project/uyuni/pull/2665 the `Create Guest` dialog in the `Virtualization > Guests` tab for Salt minions allows to create VMs using an autoinstallation profile or using a CDROM ISO or even using an external PXE configuration.

Not sure where those should be mentioned... maybe in `client-configuration/pages/virt-xenkvm.adoc` since this already contains similar documentation for traditional systems. Or maybe in `reference/pages/systems/system-details/sd-virtualization.adoc`?

Also just realized that the whole virtualization UI documentation has been commented out in `client-configuration/pages/virtualization.adoc`... would be nice to have it in the reference guide instead.

**Comment by Loquacity** [comment]
That commented out section in the Client Cfg needs to be turned into proper procedures. The basics already exist in the Ref Guide here: https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/reference/systems/system-details/sd-virtualization.html

Although it all needs to be updated for the Salt stuff.

**Comment by cbosdo** [comment]
> That commented out section in the Client Cfg needs to be turned into proper procedures, which would then include the new methods for creating a guest. The basics already exist in the Ref Guide here: https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/reference/systems/system-details/sd-virtualization.html

Thanks for the explanation and the link.
