### ISSUE TITLE
Automate packages for various output formats

### ISSUE THREAD

**Issue by jcayouette** [uyuni-project/uyuni-docs#658]
Having a distinct repo for the playbooks would allow us to control output formats using branches. Investigate.

susecom-4.1
webui-4.1
etc.

Otherwise it is extremely easy to use the wrong theme during publication.

**Comment by paususe** [comment]
What is this about? 

How would we combine the playbooks repo and the content repo? 

Why don't we just modify the Makefile (possibly adding some new intermediate target) so that it modifies antora.yml/suma-site.yml/uyuni-site.yml before building, more or less like what we do for translations?

**Comment by paususe** [comment]
@jcayouette ping. What is this about?

**Comment by jcayouette** [comment]
Ah, we can drop this idea.  Generating via makefiles and code is a much better solution!
