### ISSUE TITLE
missing icon in documentation

### ISSUE THREAD

**Issue by dirkmueller** [uyuni-project/uyuni-docs#695]
## Documentation Update Required

https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/reference/patches/patch-list-all.html

there is a "image:spacewalk-icon-enhancement.svg" where there should be an icon, looking like a typo somewhere.

**Comment by dirkmueller** [comment]
![image](https://user-images.githubusercontent.com/1029152/99959809-f2137e80-2d8b-11eb-9fbb-6271620e86c0.png)

**Comment by Loquacity** [comment]
huh! We'll have to track it down. Thanks for the report :)
