### ISSUE TITLE
Uyuni -4.0.2 - wrong link from Monitoring tab to Administration Docs

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni-docs#7]
I have noticed the link (see screenshot ) from Monitoring Tab to Prometheus is wrong.

Current:
`https://uyuni.localdomain.com/docs/administration/pages/prometheus.html` 

Correct one should be:
`https://uyuni.localdomain.com/docs/uyuni/administration/monitoring.html`
![Screenshot 2019-09-06 at 01 30 06](https://user-images.githubusercontent.com/22281444/64388014-65758700-d046-11e9-9674-7af8fb04928e.png)

**Comment by Loquacity** [comment]
@cbbayburt are you able to help here?

**Comment by cbbayburt** [comment]
@Loquacity, is this closed by mistake?

**Comment by Loquacity** [comment]
Oh, yep, sorry, too many issues!

**Comment by Loquacity** [comment]
I believe this has been addressed now.
