### ISSUE TITLE
Client configuration guide pdf missing

### ISSUE THREAD

**Issue by ktsamis** [uyuni-project/uyuni-docs#700]
## Documentation Update Required

This link in the project home is 404:
https://www.uyuni-project.org/doc/2020.09/uyuni_client_configuration_guide.pdf

## What does the documentation say now?

Missing for now

## What change is required?

Complete document needs adding

## Subject Matter Expert (SME)

REQUIRED: Who is the subject matter expert for this topic?

## Version

Which version of the software is this feature/update expected to land in? 2020.11
Which version of the documentation must this feature/update land in? 
Does the content need to be backported to previous documentation versions?

**Comment by Loquacity** [comment]
@juliogonzalez I think this one is for you.

The link on the docs index works just fine, the link that is broken is the one on https://www.uyuni-project.org/pages/stable-version.html

**Comment by juliogonzalez** [comment]
`uyuni_client-configuration_guide.pdf`, that's the correct nam, and not `uyuni_client_configuration_guide.pdf`.

@ktsamis please send a PR for the website repo: https://github.com/uyuni-project/uyuni-project.github.io

**Comment by juliogonzalez** [comment]
Will be fixed by https://github.com/uyuni-project/uyuni-project.github.io/pull/32 when 2020.11 goes out.
