### ISSUE TITLE
Document ISS troubleshooting [WAS: Integrate TID 000019792]

### ISSUE THREAD

**Issue by moio** [uyuni-project/uyuni-docs#708]
## Documentation Update Required

Integrate information in https://www.suse.com/support/kb/doc/?id=000019792

## What does the documentation say now?

Nothing regarding a typical ISS troubleshooting step.

## What change is required?

A general note that, in case of ISS errors, both the ISS-Master-side and the ISS-Slave-side caches can be cleared and that can sometimes resolve the problem (in case we had a bug that resulted in cache corruption, and we later fixed it, but caches remained corrupd).

## Subject Matter Expert (SME)

@moio

## Version

Which version of the software is this feature/update expected to land in?

**Already out in all versions.**

Which version of the documentation must this feature/update land in?

**Ideally in all versions (in addition to the TID above).**

Does the content need to be backported to previous documentation versions?

**yes**

**Comment by Loquacity** [comment]
ISS is documented in the Admin Guide, so let's add this to the Admin Troubleshooting section.
