### ISSUE TITLE
Update to postgresql13

### ISSUE THREAD

**Issue by jordimassaguerpla** [uyuni-project/uyuni-docs#711]
We need to update this page by adding a 12 to 13 migration:

https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/server-major-upgrade-uyuni.html

and then add a new page for 12 to 13 migration, similar to https://www.uyuni-project.org/uyuni-docs/uyuni/upgrade/db-migration-12.html

Note, the 10 to 12 migration content is still valid.

Posgresql13 is for the upcoming SLE15SP3 while postgresql12 is for the current leap15.2, so we need to keep both migration instructions.

**Comment by Loquacity** [comment]
Hi! Can you help me work out what documentation changes are required here please?

**Comment by jordimassaguerpla** [comment]
@Loquacity I just updated the description. Sorry for the late response, this issue was a placeholder while we were developing the feature (which is WIP).

**Comment by jordimassaguerpla** [comment]
@Loquacity @keichwa : See https://github.com/uyuni-project/uyuni-docs/pull/733 .

@juliogonzalez Could you give me your feedback as well on https://github.com/uyuni-project/uyuni-docs/pull/733 ? Is this what is expected?

**Comment by juliogonzalez** [comment]
@jordimassaguerpla I never created that doc or run the procedure myself. Huber took care. I guess that if you followed what he did for the last migration, and if you tested the procedure, it should be fine. You can also check with the QA squad, as they tested the migrations.
