### ISSUE TITLE
typo in the note field chapter Nutanix

### ISSUE THREAD

**Issue by pirat013** [uyuni-project/uyuni-docs#713]
## Documentation Update Required

typo in the path

https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/client-config-overview.html

## What does the documentation say now?
VHM Setup for Nutanix:

/etc-/pki/trust/anchors

The dash is to much.

## What change is required?

/etc/pki/trust/anchors

**Comment by Loquacity** [comment]
Thanks for the report!
