### ISSUE TITLE
salt useful commands: add a better example for salt-key -l

### ISSUE THREAD

**Issue by jonsger** [uyuni-project/uyuni-docs#734]
## Documentation Update Required

`uyuni-docs/modules/salt/pages/salt-useful-commands.adoc` says
```
salt-key -l
    List public keys:
    salt-key -l
```

I think this should be changed to something like `salt-key -l all` as `salt-key -l` results in:
```
salt-key -l 
Usage: salt-key [options]

salt-key: error: -l option requires 1 argument

**Comment by Loquacity** [comment]
Thanks for the report!
