### ISSUE TITLE
content clicking issue

### ISSUE THREAD

**Issue by carbseater** [uyuni-project/uyuni-docs#748]
## Documentation Update Required

![problem1](https://user-images.githubusercontent.com/59422042/103147678-b51d1c00-477d-11eb-9d6d-5a06436c2d02.JPG)
Clicking on the content "What is Uyuni ?" should show the heading of paragraph i,e "What is Uyuni ?"

## What does the documentation say now?
![problem](https://user-images.githubusercontent.com/59422042/103147896-67a1ae80-477f-11eb-869f-4d209a2966b4.JPG)
When clicks on the content of the page it does not show the actual heading rather than showing paragraph.

## What change is required?

I think the #id of the anchor tags in Content is not working properly, it needs to target it correctely

## Subject Matter Expert (SME)

Joseph Cayouette @jcayouette

## Version

Which version of the software is this feature/update expected to land in?
-> Don't know properly

Which version of the documentation must this feature/update land in?
 -> Uyuni 2020.11

Does the content need to be backported to previous documentation versions?
-> I think so.

**Comment by Loquacity** [comment]
Thanks for the report!

**Comment by carbseater** [comment]
> Thanks for the report!

Can I work upon this issue? @Loquacity

**Comment by Loquacity** [comment]
> > Thanks for the report!
> 
> Can I work upon this issue? @Loquacity

Of course, just create a PR for your changes, and tag @jcayouette and myself.
