### ISSUE TITLE
Public Cloud Documentation - Enhancement

### ISSUE THREAD

**Issue by stephenmogg** [uyuni-project/uyuni-docs#752]
## Documentation Update Required

Improve Client Configuration Section - with some public cloud detail on how to connect PAYG clients to SUMA. (AWS)

## What does the documentation say now?

There is no section in 'client configuration' which covers connecting public cloud clients to SUSE Manager Server.

## What change is required?
There are two prerequisites that need to be met before registering a client. The documentation for the prerequisites is available is in the server installation piece and I could not find it in the client configuration:
There is some detail in 4.0 which has a separate Public cloud document, but this is not linked in 4.1.
 
Uninstall regionServiceClientConfigEC2. 
The only place I could find how to uninstall the service in the documentation is focused on the server installation.
Link: https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/public-cloud.html#_instance_requirements

Creating a unique client id
Link: https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/administration/public-cloud.html#registration-of-cloned-systems

What content needs to be added?
As above.

## Subject Matter Expert (SME)

REQUIRED: Who is the subject matter expert for this topic?
You are welcome to speak to me on the topic and I will help where I can. (stephen.mogg@suse.com)

## Version
Which version of the software is this feature/update expected to land in?
4.1
Which version of the documentation must this feature/update land in?
The next version?

Does the content need to be backported to previous documentation versions?
Maybe

**Comment by Loquacity** [comment]
@stephenmogg Did you check the Public Cloud Quick Start Guide? https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/quickstart-public-cloud/qs-publiccloud-overview.html It has a section for Client registration, and I'm wondering if that is accurate, or could use some updates?

All PC content was consolidated to the Install Guide and the QS:PC Guide fairly recently, but the ongoing confusion here makes me think we should remove all content from the Install Guide and just point to the QS Guide, to try and get everything in one spot. By that token, I think we can probably add a section to the Client Config Guide, but it might be best to just use it to point to the QS:PC guide, rather than try and duplicate it. What are your thoughts?

**Comment by stephenmogg** [comment]
Hi ,

When I checked before the holiday, I could not see the Public Cloud quickstart guide linked from the SUSE Manager 4.1 Documentation home page, is it new, or was I not paying enough attention ☺

Either way, this QS client section still does not cover the client configuration piece for PAYG clients (i.e. removing the relevant packages that connect you to the Public Cloud Update Infrastructure or solve the registering cloned guests) issue that will definitely occur in AWS..

But to your comment, this should either be all in the install guide, where you have a public cloud section for install, setup and client config….  or all in a separate QuickStart.

I would rather see it in the mainstream docs.  (Separate ‘Public Cloud’ sections).

Stephen

**Comment by Loquacity** [comment]
> Hi , When I checked before the holiday, I could not see the Public Cloud quickstart guide linked from the SUSE Manager 4.1 Documentation home page, is it new, or was I not paying enough attention  

It was new in 4.1, so it's new but not that new :wink: 

> Either way, this QS client section still does not cover the client configuration piece for PAYG clients (i.e. removing the relevant packages that connect you to the Public Cloud Update Infrastructure or solve the registering cloned guests) issue that will definitely occur in AWS.. 

OK, I'll work on getting that written up.

> But to your comment, this should either be all in the install guide, where you have a public cloud section for install, setup and client config…. or all in a separate QuickStart. I would rather see it in the mainstream docs. (Separate ‘Public Cloud’ sections). 

I can see the value in having it as part of the rest of the docs, which is why we originally had it there. Unfortunately, though, it means the content got split up between several books which, from the feedback we got, was confusing for everyone. For now, let's put it in the QS:PC Guide (and consider a rename), just to try and get the info all in one place. We can always change it around again later on if we come up with something better, but let's give this some time for people to get used to it and see what they say.

**Comment by Loquacity** [comment]
@stephenmogg Please review https://github.com/uyuni-project/uyuni-docs/pull/768 I've uploaded a PDF version of the changes in the comments to that PR, to make it a bit easier to see what I've done.

**Comment by stephenmogg** [comment]
HI Lana,

I could not see the PDF, but reviewed the changes in Github.  It looks good so far.


  1.  Are you including a section on how to register clones machines (or referencing back to the main doc)?  All the launched instances will overwrite each other as they are registered.

  2.  Something I forgot to ask … is I worth mentioning that with PAYG instances, you will still need at least 1 real subscription for product you are managing with SUSE Manager?, this is not used against any instances, but used to open the channels at the SCC to allow the mirroring of patches.  (we still get a customers tripping up over this).  Perhaps that should be a Sales training rather than documentation ….

Finally: Thumbs up  from me for a name change.  It’s not really a quickstart, but supplementary documentation.

Finally Finally – Thanks for making the changes.

Stephen

**Comment by Loquacity** [comment]
> HI Lana, I could not see the PDF, but reviewed the changes in Github. It looks good so far. 

Apologies, I just re-uploaded for you, so hopefully it works now.

**Comment by Loquacity** [comment]
Replied in https://github.com/uyuni-project/uyuni-docs/pull/768#issuecomment-759873048

**Comment by Loquacity** [comment]
Meeting held with @paususe to discuss this on 21 Jan 2021. Defined three main methods of installing on public cloud:

1. VM on public cloud, install SUMA on-prem using unified installer.
2. VM BYOS image includes SUMA, no need to install, just set up org, etc.
3. On-demand SLES PAYG image, install SUMA on top.

@paususe to check if method 3 is recommended, as it may have cost implications for users. This could affect how/if we document the method.

Options for documenting:

1. Install Guide, have a public cloud section within the three broader categories (reqs, install, set up), include all methods.
2. Install Guide, have a public cloud section as its own category, which goes through all methods.
3. Public Cloud Guide (either replacing or in addition to the Quick Start) which discusses all three methods in depth.


(Moving this card to blocked while I wait for Pau to advise).

**Comment by Loquacity** [comment]
Meeting held with @paususe 2021-02-22. Determined that we will go with this method:

> 1. Install Guide, have a public cloud section within the three broader categories (reqs, install, set up), include all methods.

Then we can revert the Quick Start Guide to being only quick start info. As an additional note: there is scope for adding a public cloud workflow to the new cookbook in 4.2 as well.

Still to do: Confirm if method 3 ("On-demand SLES PAYG image, install SUMA on top.") is recommended.

**Comment by Loquacity** [comment]
Hi @stephenmogg Sorry for the delay in completing this. Please take a look at PR #768 (I have uploaded some PDFs and images to make reviewing a bit easier) and let me know what you think.
