### ISSUE TITLE
Quick start guide review feedback

### ISSUE THREAD

**Issue by aaannz** [uyuni-project/uyuni-docs#766]
Good job on the quick start guide, I thing even people new to Uyuni can configure and start using it following the guide. There are however some bits I noticed:

1) 
  Installation - when adding repository, repository is not specified:
  
  ```zypper ar https://download.opensuse.org/$repo uyuni-server-stable```
  
  should be
  
  ```zypper ar https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/ uyuni-server-stable```
  
  or at least ```$repo``` specified somewhere with proper repo url, similarly as is done for proxy installation.

2)
  At ```Optional Procedure: Entering Organization Credentials``` there is `SUSE Manager WebUI` mentioned instead of `Uyuni WebUI`

3)
  Option ```Use SSL``` was removed, now SSL is always used during `configure-proxy.sh` run.

4)
  Why are ```Enable PXE Booting``` and ```Configure DHCP for PXE through Proxy```  present in quick start? IMO these do not belong to quick start guide as they are not really required for Uyuni to work and there is also not a word about cobbler configuration without it it wont work as expected.

5)
  I'm not sure, but shouldn't ```Register a Proxy``` be before ```Set Up the Proxy```?

6)
Why is there section ```Reinstalling a Proxy``` when only is does is to point to the documentation? Wouldn't it made more sense to add generic section like *For more information about Uyuni see https://www.uyuni-project.org/uyuni-docs/uyuni/index.html*?

**Comment by Loquacity** [comment]
Thanks for the comprehensive review!
