### ISSUE TITLE
Missing example autoyast profile for SLES 15 SPX & Mention to upgrade profiles from previous major release

### ISSUE THREAD

**Issue by raulosuna** [uyuni-project/uyuni-docs#783]
## Documentation Update Required

Autoyast example profile for SLES 15 SPX (GA/SP1/SP2 and SP3 in the future) is needed. Many customers don't have a clue about how to generate one, this generates a lot of support cases. A TID is not the place where this should be documented. We're receiving a lot of support cases about this, many of which end up in bugzilla/L3 generating extra workload on Engineering.
In addition to this, most of the queries are for upgrades, rather than new installations (SLES 11 SP4 to SLES 12 SPX, or SLES 12 SPX to SLES 15 SPX). Should there be any changes in the related autoyast profiles, that should be mentioned here (or at least, a link to the documentation for it, in case it's too long for everything to be included in the same place)

## What does the documentation say now?

There's a basic autoyast profile for SLES 12 SPX installation.

## What change is required?

We'd kindly ask for the same in SLES 15 family,

## Subject Matter Expert (SME)

Both SUSE Manager and Yast teams.

## Version

Which version of the software is this feature/update expected to land in?
All supported versions of SUSE Manager: 4.0 & 4.1. 4.2 is about to be released, so this might need to be considered as well.
Which version of the documentation must this feature/update land in?
4.0, 4.1, 4.2
Does the content need to be backported to previous documentation versions?
Yes, 4.0.

**Comment by Loquacity** [comment]
Hi Raul, thanks for the report. Which document are you looking at?

**Comment by mcalmer** [comment]
We have this https://github.com/SUSE/manager-build-profiles/tree/master/AutoYaST/SLES-15-SP2-installation

**Comment by raulosuna** [comment]
> Hi Raul, thanks for the report. Which document are you looking at?

My bad, I thought that the "contribute" button would save the exact page of the documentation I was reporting. It is located here:

https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/autoyast-example.html

Michael's examples would fit here pretty well. I assume that if a SLES for SAP example file is provided for SLES 15, the same should exist for SLES 12.

For both cases, the existing SLES 12 SPX profile and this new one for SLES 15 SPX, it would be nice to have a mention on what to modify for the case of an upgrade from the previous major release(SLES 11 to 12 and SLES 12 to 15) instead of a new installation. I assume nothing needs to be changed on the autoyast profile, only in the web-UI (?). That would rather fit in https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/autoinst-setup.html (I guess, but please organize it as you consider best). Let me know if this needs to go in a different issue.

**Comment by mcalmer** [comment]
@Loquacity @raulosuna The idea of that git repo is, to collect all kind of examples the customers need. We cannot print every example in the manual, so the idea was to link this git in the docs and if something is missing, just do a Pull Request and we add a new profile.
We have examples for install and update, for different SLE versions and base products.

Please review the hole content and tell us what is missing or provide missing examples with a PR.

**Comment by raulosuna** [comment]
You're right, I completely overlooked that there's already a link to the github repository...

**Comment by Loquacity** [comment]
Yes, @keichwa did that switch last year, IIRC. I'll take a look and see if we can improve things a little.
