### ISSUE TITLE
configure-proxy.sh: Document the last prompted parameter

### ISSUE THREAD

**Issue by calancha** [uyuni-project/uyuni-docs#825]
## Documentation Update Required

- `modules/installation/pages/uyuni-proxy-setup.adoc`

I am following the doc to set up a 4.2 SUMa proxy.

I find it useful that the doc provides a brief description of each
parameter of `configure-proxy.sh` with a suggested default..

The last question is not documented:
`Activate advertising proxy via SLP? [Y/n]`

Could we add 1-2 lines to explain this parameter and suggest a sensible default?

## What does the documentation say now?

Description of existing documentation.
Include screenshot if required.

## What change is required?
Document the last prompted parameter by the script `configure-proxy.sh`.

What content needs to be added?
Include description of content, and potential location of new content in the docs suite.

- `modules/installation/pages/uyuni-proxy-setup.adoc`
Document what it does the parameter and suggest a default.

## Subject Matter Expert (SME)

REQUIRED: Who is the subject matter expert for this topic?
I don't know.
## Version

Which version of the software is this feature/update expected to land in?
4.2
Which version of the documentation must this feature/update land in?
Does the content need to be backported to previous documentation versions?
To be decided by doc experts.

**Comment by Loquacity** [comment]
@paususe Who is a good SME for this?

**Comment by paususe** [comment]
@jordimassaguerpla could you please help here?

**Comment by keichwa** [comment]
I guess here we can say something general only:

> If you use Service Location Protocol (SLP) in your network topology, consider to enable it.
> For background informationabout SLP, see SLE documentation [I'll try to find the proper location there]

If SLE does not explain it, we can link to https://en.wikipedia.org/wiki/Service_Location_Protocol.  What do you think?

**Comment by Loquacity** [comment]
> I guess here we can say something general only:
> 
> > If you use Service Location Protocol (SLP) in your network topology, consider to enable it.
> > For background informationabout SLP, see SLE documentation [I'll try to find the proper location there]
> 
> If SLE does not explain it, we can link to https://en.wikipedia.org/wiki/Service_Location_Protocol. What do you think?

I wouldn't link to Wikipedia. I think if SLE doesn't explain it, we should.

**Comment by mcalmer** [comment]
SLP seems to be dead. AFAIK SUSE wanted to use it to find services in the network. But I never got feedback and we have no tooling in suma bootstrap to use it.

We should think about dropping SLP.

**Comment by keichwa** [comment]
ok, thanks for feedback, @mcalmer .  If we want to drop it, it would make sense to create a spacewalk issue, imo.  I can do it if not already done.

**Comment by Loquacity** [comment]
@keichwa Do we have a course of action here?

**Comment by keichwa** [comment]
I now created https://github.com/SUSE/spacewalk/issues/14539 that now blocks our issue.

**Comment by 0rnela** [comment]
We seem to be in the loop here, between this issue and the github one mentioned above which currently points to this card.

Is there any progress or room for resolution at some point?

@keichwa @mcalmer

**Comment by keichwa** [comment]
I think this is still blocked.

**Comment by keichwa** [comment]
We'll adjust the docs when  SUSE/spacewalk#14539 is dealt with.

**Comment by tacerus** [comment]
Should we add a note in https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/uyuni-server-setup.html regarding this? I just had to Google around quite a while to find this issue after wondering what the option is about.
