### ISSUE TITLE
Published docs have some kind of issue with initing highlight.js

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#826]
## Change Required

I guess there is something small broken in Antora for the published SUMA 4.1 & SUMA 4.0 docs.
The highlight.js syntax highlighter does not seem to work properly.

The docs put the following error on the console:

```
Uncaught ReferenceError: hljs is not defined
    <anonymous> https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/large-deployments/large-deployments-overview.html:1751
```

The line referenced is this one:
```
<script>hljs.initHighlighting()</script>
```

It appears the highlight.js library itself does load though, but perhaps this is a timing issue, and the library loads too late.

## Version

SUMA 4.0 & SUMA 4.1 docs

**Comment by Loquacity** [comment]
@jcayouette this is probably one for you :wink:

**Comment by jcayouette** [comment]
@sknorr Thanks, I saw this when I worked over our new API docs. I figured out the issue. 

If you check the example link on the upstream site, their instructions are incorrect for adding the styles. They neglected to include the *https* in the link. Updating our themes.

**Comment by sknorr** [comment]
@jcayouette `//` at the beginning is actually correct, it's used for "match whatever protocol is already in use for the rest of the site", meaning if you the original document is using plain HTTP, the request will use plain HTTP; if the original site is using HTTPS, the request will also use HTTPS.

As I said, the library itself is downloaded correctly. My suspicion is just that `hljs.initHighlighting()` is applied _before_ the library is downloaded. You might have more success with adding an event listener that checks whether the document has finished loading correctly already, like:

```
<script>window.addEventListener("load", function (e) { hljs.initHighlighting(); }, false);</script>
```

**Comment by jcayouette** [comment]
@sknorr Great! Thanks.

**Comment by Loquacity** [comment]
@jcayouette Is there a PR somewhere that I'm missing?
