### ISSUE TITLE
Fix link to AWS Region/Zones doc

### ISSUE THREAD

**Issue by calancha** [uyuni-project/uyuni-docs#830]
## Documentation Update Required

In this file `modules/client-configuration/pages/vhm-aws.adoc`
you can read:
"For more information about setting regions and zones, see xref:client-configuration:vhm.adoc[]."
but in such a link there is no discussion on Region/Zones.

According with the following screenshot, the right target for this link seems to be:
`modules/client-configuration/pages/virtualization.adoc`
(`#_susesupport_and_vm_zones`)

![right-target-Screenshot from 2021-03-04 10-05-17](https://user-images.githubusercontent.com/13642261/109939286-32f72980-7cd1-11eb-9f7b-c307aee99998.png)

## What change is required?
Fix the target of a link.

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?
Any member of the doc squad.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Found in a SUMa 4.2.0.Alpha2

**Comment by jcayouette** [comment]
@calancha Thanks adjusting now.

**Comment by calancha** [comment]
This could be fixed another way around: instead of update the target, you can move the relevant section
to the current link (that is already discussing clouds).  I let decide doc experts what is better.
Please, do not forget to fix in the same page  `i1234567890abcdef0` -> `i-1234567890abcdef0` (not mentioned in my report).
