### ISSUE TITLE
/home/coyote/... directory structure in the SUMA 4.x tarballs

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#853]
## Update required

The tarballs of the SUMA 4.0 & 4.1 PDFs contain the path `/home/coyote/...` which looks a little off. :)
In addition, all other other archives on the site are Zip archives (mostly for compatibility and because we don't actually need Unix permissions for documentation archives), not Tars.

## What change is required?

* required: not quite sure how the tarballs are built currently, but a `cd /path/to/the/pdf/builds` before building the archives should prevent the issue from appearing (but I've always shied using `tar`, so there may be a better option than a `cd`).
* nice-to-have: switch to Zip archives.
 

## Subject Matter Expert (SME)

@jcayouette

## Version

4.0 & 4.1

**Comment by jcayouette** [comment]
Thanks, known issue now for some time. It looks like the tarball command is set correctly so I am a little confused as to whats happening here. I will run it by @paususe since he is the Makefile king here :P

Right, I will adjust to use zip!

**Comment by Loquacity** [comment]
@jcayouette Sitrep on this?

**Comment by jcayouette** [comment]
I have converted the Makefiles to use zip, but I am still fiddling with the variables. I hope to have something functional this afternoon!
