### ISSUE TITLE
Add Alibaba Cloud Linux 2 docs

### ISSUE THREAD

**Issue by paususe** [uyuni-project/uyuni-docs#866]
Reminder issue.

Code PR:
https://github.com/uyuni-project/uyuni/pull/3468

**Comment by Loquacity** [comment]
@paususe Is there a docs PR open for this?

**Comment by paususe** [comment]
In fact it was merged already

**Comment by Loquacity** [comment]
> In fact it was merged already

881 is still open though?

**Comment by paususe** [comment]
> > In fact it was merged already
> 
> 881 is still open though?

Wooot? You are right, it seems I forgot to merge
