### ISSUE TITLE
Documentation on `configure-tftpsync.sh`

### ISSUE THREAD

**Issue by calancha** [uyuni-project/uyuni-docs#888]
## Documentation Update Required

Seen at `modules/client-configuration/pages/cobbler.adoc`,
where it is documented `Procedure: Configuring TFTP on a Proxy`.
```
. On the {productname} Proxy, as root, run the [command]``configure-tftpsync.sh`` script.
. The script interactively asks you for details on the host names and IP addresses of the {productname} Server and Proxy, as well for the location of the [path]``tftpboot`` directory on the Proxy.

For more information, use the [command]``configure-tftpsync.sh --help`` command.
```

I see two issues:
- `--help` is not a valid option for such a script.
- There is no `more information` to see when calling the command w/o arguments (just the signature).
```
$ configure-tftpsync.sh --help
Invalid hostname for proxy: --help
usage: configure-tftpsync.sh proxy1.domain.top proxy2.domain.top ...
```
- The text mentions that the script is interactive, but it's not.

Maybe that description has been copied and pasted from some other similar command.

## What does the documentation say now?
It says that the script is interactive, and it accepts a `--help` option.

## What change is required?
The script is not interactive and it doesn't accept a `help` option.
Instead of refer to the script help, we might add any useful information in the text.

## Subject Matter Expert (SME)

N/A
## Version

Found in the master branch of the SUMa documentation.

**Comment by Bischoff** [comment]
The ``help`` option works, see screenshot.

**Comment by Bischoff** [comment]
![image](https://user-images.githubusercontent.com/1932575/116240435-1c66cf00-a764-11eb-93c7-01d5d8974fd2.png)

**Comment by Bischoff** [comment]
It might also be the interactive mode works. At least it should, according to this help page.

**Comment by 0rnela** [comment]
Closing this issue as the entire chapter was rewritten and also @Bischoff had provided screenshot for the --help option.
