### ISSUE TITLE
Add more detailed instructions about image buildhost in case of Raspberry Pi image building

### ISSUE THREAD

**Issue by lkotek** [uyuni-project/uyuni-docs#937]
## Documentation Update Required

We need to clarify which architectures are expected to be used in case of kiwi image build hosts for Raspberry Pi.

## What does the documentation say now?

```To build all kinds of images with {productname}, create and configure a build host. OS Image build hosts are Salt clients running on {sles} 15 SP2, {sles} 12 (SP3 or later) or {sles} 11 SP4.```

## What change is required?

We need to include information about build host requirements for Raspberry Pi image building. Currently it is possible to build kiwi image **for** Raspberry PI **at** SLE15SP3 system running Raspberry PI (aarch64 architecture). 

We need to clarify if this is only option or if there is also option to use x86_64 architecture based build host for this purpose (+ specific configuration for this build host as this setup fails to build by default).

## Subject Matter Expert (SME)

@nadvornik 

## Version

This is related to SUSE Manager 4.2 only.

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by lkotek** [comment]
@juliogonzalez just to be aware - I am not allowed to assign or attach to the projects.

**Comment by juliogonzalez** [comment]
@lkotek we'll talk to the doc squad next week about it. As of today, this is expected at the uyuni-docs repo.

**Comment by keichwa** [comment]
thanks for the proposal!
