### ISSUE TITLE
Use smaller/more-branding-conscious cover image for SUMA PDFs

### ISSUE THREAD

**Issue by sknorr** [uyuni-project/uyuni-docs#946]
## Documentation Update Required

The cover pages of SUMA PDFs currently use a 500KB PNG version of the Geeko tail I created ages ago from the old SUSE logo. Since then, the logo has changed and there's also a branding rule against creating cutouts of the SUSE logo. The doc team's PDF will thus switch to one of the lines patterns. For the moment, it's this one, stolen from the "basic business document" on Imagerelay, then cleaned up: [pattern.zip](https://github.com/uyuni-project/uyuni-docs/files/6433741/pattern.zip). (Sorry, I needed to ZIP this, as GitHub does not accept SVG uploads here.) Obviously, you can pick a more exciting one off Imagerelay (or not^^).

## What change is required?

Change background image in antora-pdf settings.

## Version

4.2 maybe? not sure

**Comment by jcayouette** [comment]
@sknorr Is this pattern on a white background? Or the Pine green?

**Comment by sknorr** [comment]
White. Which is also friendlier to people who still print documents.

**Comment by jcayouette** [comment]
I will update this for our next MU.

**Comment by jcayouette** [comment]
Updated branding in 4.2.4
