### ISSUE TITLE
Client-Registration OSAD Port correct?

### ISSUE THREAD

**Issue by costcc** [uyuni-project/uyuni-docs#951]
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

https://documentation.suse.com/external-tree/en-us/suma/4.0/suse-manager/client-configuration/contact-methods-osad.html
SUSE Manager->
Client Configuration Guide->
Client Contact Methods->
OSAD

## What does the documentation say now?

Troubleshooting OSAD
If your OSAD clients cannot connect to the server, or if the jabberd service takes a lot of time responding to port 5552, it could be because you have exceeded the open file count.

## What change is required?

Is the port mentioned in Documentation correct?
Or should this port must be 5222

## Subject Matter Expert (SME)

Who is the subject matter expert for this topic (if known)?

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

## Internal SUSE Reporters

This repository is public.
If you are reporting an issue that needs to remain company confidential, please use the internal Bugzilla instance instead.

**Comment by 0rnela** [comment]
This issue has bee addressed in the PR above.
